import { defineSpellingEntries, reference } from './schema.js';

export const COMPOUND_SPELLING_ENTRIES = defineSpellingEntries(
    'compound',
[
        reference(48, "deunggyotgil", "saisiot", "exact", "catalog", "등굣길 / 등교길", "등굣길", "학교에 가는 길은 ‘등굣길’이라고 적어요.", ["등굣길에 친구를 만났어요.","비 오는 등굣길에는 우산을 써요."]),
        reference(49, "hagyotgil", "saisiot", "exact", "catalog", "하굣길 / 하교길", "하굣길", "학교에서 집으로 돌아오는 길은 ‘하굣길’이라고 적어요.", ["하굣길에 도서관에 들렀어요.","하굣길에는 차를 조심해요."]),
        reference(50, "namunnip", "saisiot", "exact", "catalog", "나뭇잎 / 나무잎", "나뭇잎", "나무에 달린 잎은 ‘나뭇잎’이라고 적어요.", ["가을바람에 나뭇잎이 떨어졌어요.","초록 나뭇잎이 햇빛에 반짝여요."]),
        reference(51, "konmul", "saisiot", "exact", "catalog", "콧물 / 코물", "콧물", "코에서 흐르는 액체는 ‘콧물’이라고 적어요.", ["감기에 걸려 콧물이 났어요.","콧물이 나면 휴지로 닦아요."]),
        reference(52, "itmom", "saisiot", "exact", "catalog", "잇몸 / 이몸", "잇몸", "이를 둘러싸고 있는 살은 ‘잇몸’이에요.", ["이를 닦을 때 잇몸도 살살 닦아요.","잇몸이 아파서 치과에 갔어요."]),
        reference(53, "haetbyeot", "saisiot", "exact", "catalog", "햇볕 / 해볕", "햇볕", "해가 내리쬐는 뜨거운 기운은 ‘햇볕’이라고 적어요.", ["따뜻한 햇볕을 쬐었어요.","강한 햇볕을 피하려고 모자를 썼어요."]),
        reference(54, "araenni", "saisiot", "exact", "catalog", "아랫니 / 아래니", "아랫니", "아래쪽에 난 이는 ‘아랫니’라고 적어요.", ["아랫니가 흔들리기 시작했어요.","아랫니까지 꼼꼼하게 닦았어요."]),
        reference(56, "jeonsetjip", "saisiot", "exact", "catalog", "전셋집 / 전세집", "전셋집", "전세로 빌려 사는 집은 ‘전셋집’이라고 적어요.", ["새 전셋집으로 이사했어요.","부모님이 전셋집을 알아보셨어요."]),
        reference(57, "chatjan", "saisiot", "exact", "catalog", "찻잔 / 차잔", "찻잔", "차를 따라 마시는 잔은 ‘찻잔’이라고 적어요.", ["찻잔에 따뜻한 차를 따랐어요.","예쁜 찻잔을 조심히 들었어요."]),
        reference(58, "gichatgil", "saisiot", "exact", "catalog", "기찻길 / 기차길", "기찻길", "기차가 다니는 길은 ‘기찻길’이라고 적어요.", ["기찻길 가까이에서는 조심해야 해요.","기찻길을 따라 기차가 달려요."]),
        reference(59, "badatga", "saisiot", "context", "catalog", "바닷가 / 바다가", "바닷가", "바다와 땅이 맞닿은 곳은 ‘바닷가’예요.", ["여름에 바닷가에서 모래성을 쌓았어요.","바닷가에 파도 소리가 들려요."], {"detectionPatterns":[{"text":"바다가에서","target":"바다가","right":"바닷가","lookup":"바닷가"},{"text":"바다가에 파도","target":"바다가","right":"바닷가","lookup":"바닷가"}]}),
        reference(60, "naetga", "saisiot", "context", "catalog", "냇가 / 내가", "냇가", "냇물의 가장자리는 ‘냇가’라고 적어요.", ["냇가에서 작은 돌을 관찰했어요.","비가 온 뒤 냇가에 물이 불었어요."], {"detectionPatterns":[{"text":"내가에서","target":"내가","right":"냇가","lookup":"냇가"},{"text":"뒤 내가에 물","target":"내가","right":"냇가","lookup":"냇가"}]}),
        reference(61, "gwitsongmal", "saisiot", "exact", "catalog", "귓속말 / 귀속말", "귓속말", "남의 귀 가까이에 대고 작은 소리로 하는 말은 ‘귓속말’이에요.", ["친구가 내게 귓속말을 했어요.","수업 시간에는 귓속말을 하지 않아요."]),
        reference(62, "meoritsok", "saisiot", "exact", "catalog", "머릿속 / 머리속", "머릿속", "생각이나 기억이 들어 있다고 여기는 곳은 ‘머릿속’이라고 적어요.", ["좋은 생각이 머릿속에 떠올랐어요.","머릿속으로 답을 계산했어요."]),
        reference(63, "jangmatbi", "saisiot", "exact", "catalog", "장맛비 / 장마비", "장맛비", "장마 때 내리는 비는 ‘장맛비’라고 적어요.", ["장맛비가 여러 날 내렸어요.","장맛비에 우산이 젖었어요."]),
        reference(64, "jondaenmal", "saisiot", "exact", "catalog", "존댓말 / 존대말", "존댓말", "사람을 높여 말하는 표현은 ‘존댓말’이에요.", ["어른께 존댓말을 사용해요.","친구와 존댓말 연습을 했어요."]),
        reference(207, "expansion-dwikkumchi", "no-saisiot", "exact", "expansion", "뒤꿈치 / 뒷꿈치", "뒤꿈치", "발의 맨 뒤쪽을 가리키는 말이에요. ‘뒷꿈치’가 아니라 ‘뒤꿈치’로 적어요.", ["새 신발이 뒤꿈치에 닿아요.","뒤꿈치를 들고 조용히 걸었어요."]),
        reference(235, "expansion-haenim", "no-saisiot", "exact", "expansion", "해님 / 햇님", "해님", "해를 사람처럼 정답게 이르는 말이에요. ‘햇님’가 아니라 ‘해님’로 적어요.", ["구름 뒤에서 해님이 나왔어요.","해님이 온 세상을 밝게 비추어요."]),
        reference(270, "expansion-dwitongsu", "no-saisiot", "exact", "expansion", "뒤통수 / 뒷통수", "뒤통수", "머리의 뒷부분을 가리키는 말이에요. ‘뒷통수’가 아니라 ‘뒤통수’로 적어요.", ["넘어지며 뒤통수를 부딪쳤어요.","뒤통수에 모자를 단단히 눌러썼어요."]),
        reference(271, "expansion-golchitgeori", "saisiot", "exact", "expansion", "골칫거리 / 골치거리", "골칫거리", "해결하기 어려운 문제를 가리켜요. 이 말은 사이시옷을 살려 ‘골칫거리’로 적어요.", ["숙제가 큰 골칫거리는 아니에요.","쓰레기가 마을의 골칫거리가 되었어요."]),
        reference(272, "expansion-gwigatgil", "saisiot", "exact", "expansion", "귀갓길 / 귀가길", "귀갓길", "집으로 돌아가는 길을 뜻해요. 이 말은 사이시옷을 살려 ‘귀갓길’로 적어요.", ["귀갓길에 친구와 인사했어요.","어두운 귀갓길에는 조심해서 걸어요."]),
        reference(273, "expansion-kkaennip", "saisiot", "exact", "expansion", "깻잎 / 깨잎", "깻잎", "깨의 잎을 가리키는 말이에요. 이 말은 사이시옷을 살려 ‘깻잎’로 적어요.", ["텃밭에서 깻잎을 땄어요.","깻잎에서 향긋한 냄새가 나요."]),
        reference(274, "expansion-narutbae", "saisiot", "exact", "expansion", "나룻배 / 나루배", "나룻배", "나루를 오가는 작은 배를 말해요. 이 말은 사이시옷을 살려 ‘나룻배’로 적어요.", ["나룻배가 강을 건넜어요.","사공이 나룻배를 저었어요."]),
        reference(275, "expansion-naitgap", "saisiot", "exact", "expansion", "나잇값 / 나이값", "나잇값", "나이에 어울리는 말이나 행동을 뜻해요. 이 말은 사이시옷을 살려 ‘나잇값’로 적어요.", ["나잇값을 하라는 말씀을 들었어요.","나잇값에 맞게 책임 있게 행동했어요."]),
        reference(276, "expansion-noraenmal", "saisiot", "exact", "expansion", "노랫말 / 노래말", "노랫말", "노래의 가사를 뜻해요. 이 말은 사이시옷을 살려 ‘노랫말’로 적어요.", ["아름다운 노랫말을 따라 불렀어요.","노랫말의 뜻을 생각해 보았어요."]),
        reference(277, "expansion-dwinnil", "saisiot", "exact", "expansion", "뒷일 / 뒤일", "뒷일", "어떤 일이 끝난 뒤의 일을 뜻해요. 이 말은 사이시옷을 살려 ‘뒷일’로 적어요.", ["뒷일은 내가 정리할게요.","지금은 뒷일을 걱정하지 마세요."]),
        reference(278, "expansion-deungdaetbul", "saisiot", "exact", "expansion", "등댓불 / 등대불", "등댓불", "등대에서 비추는 불빛을 말해요. 이 말은 사이시옷을 살려 ‘등댓불’로 적어요.", ["멀리 등댓불이 반짝였어요.","등댓불이 배의 길을 밝혔어요."]),
        reference(279, "expansion-mandutguk", "saisiot", "exact", "expansion", "만둣국 / 만두국", "만둣국", "만두를 넣고 끓인 국을 말해요. 이 말은 사이시옷을 살려 ‘만둣국’로 적어요.", ["설날 아침에 만둣국을 먹었어요.","따뜻한 만둣국에서 김이 나요."]),
        reference(280, "expansion-meoritgyeol", "saisiot", "exact", "expansion", "머릿결 / 머리결", "머릿결", "머리카락이 이루는 결을 뜻해요. 이 말은 사이시옷을 살려 ‘머릿결’로 적어요.", ["빗질을 하니 머릿결이 고와졌어요.","바람에 머릿결이 날렸어요."]),
        reference(281, "expansion-seonjitguk", "saisiot", "exact", "expansion", "선짓국 / 선지국", "선짓국", "선지를 넣고 끓인 국을 말해요. 이 말은 사이시옷을 살려 ‘선짓국’로 적어요.", ["시장 식당에서 선짓국을 팔아요.","선짓국을 따뜻하게 끓였어요."]),
        reference(282, "expansion-sundaetguk", "saisiot", "exact", "expansion", "순댓국 / 순대국", "순댓국", "순대를 넣어 끓인 국을 말해요. 이 말은 사이시옷을 살려 ‘순댓국’로 적어요.", ["아버지는 뜨거운 순댓국을 드셨어요.","순댓국 한 그릇을 주문했어요."]),
        reference(283, "expansion-araenmaeul", "saisiot", "exact", "expansion", "아랫마을 / 아래마을", "아랫마을", "아래쪽에 있는 마을을 뜻해요. 이 말은 사이시옷을 살려 ‘아랫마을’로 적어요.", ["아랫마을까지 걸어 내려갔어요.","아랫마을에 작은 장터가 열렸어요."]),
        reference(284, "expansion-yesannil", "saisiot", "exact", "expansion", "예삿일 / 예사일", "예삿일", "보통 흔히 있는 일을 뜻해요. 이 말은 사이시옷을 살려 ‘예삿일’로 적어요.", ["매일 연습하는 것은 예삿일이 아니에요.","그 일을 예삿일처럼 넘기지 않았어요."]),
        reference(285, "expansion-jangmitbit", "saisiot", "exact", "expansion", "장밋빛 / 장미빛", "장밋빛", "장미꽃처럼 붉고 밝은 빛을 뜻해요. 이 말은 사이시옷을 살려 ‘장밋빛’로 적어요.", ["하늘이 장밋빛으로 물들었어요.","앞날을 장밋빛으로만 그리지 않아요."]),
        reference(286, "expansion-jaetbit", "saisiot", "exact", "expansion", "잿빛 / 재빛", "잿빛", "재와 같은 흐린 회색빛을 뜻해요. 이 말은 사이시옷을 살려 ‘잿빛’로 적어요.", ["비구름이 잿빛으로 변했어요.","고양이의 잿빛 털이 부드러워요."]),
        reference(287, "expansion-jeongitjul", "saisiot", "exact", "expansion", "전깃줄 / 전기줄", "전깃줄", "전기가 흐르는 줄을 뜻해요. 이 말은 사이시옷을 살려 ‘전깃줄’로 적어요.", ["새가 전깃줄에 앉았어요.","끊어진 전깃줄에는 가까이 가지 않아요."]),
        reference(288, "expansion-jogaetsal", "saisiot", "exact", "expansion", "조갯살 / 조개살", "조갯살", "조개의 껍데기 안에 든 살을 말해요. 이 말은 사이시옷을 살려 ‘조갯살’로 적어요.", ["조갯살을 넣어 국을 끓였어요.","조갯살을 깨끗이 씻었어요."]),
        reference(289, "expansion-chotbul", "saisiot", "exact", "expansion", "촛불 / 초불", "촛불", "초에 켠 불을 뜻해요. 이 말은 사이시옷을 살려 ‘촛불’로 적어요.", ["생일 케이크의 촛불을 껐어요.","바람에 촛불이 흔들렸어요."]),
        reference(290, "expansion-kotdeung", "saisiot", "exact", "expansion", "콧등 / 코등", "콧등", "코의 윗부분을 가리키는 말이에요. 이 말은 사이시옷을 살려 ‘콧등’로 적어요.", ["안경이 콧등에서 흘러내렸어요.","콧등에 땀이 맺혔어요."]),
        reference(291, "expansion-pitjul", "saisiot", "exact", "expansion", "핏줄 / 피줄", "핏줄", "피가 흐르는 관이나 혈통을 뜻해요. 이 말은 사이시옷을 살려 ‘핏줄’로 적어요.", ["손등에 파란 핏줄이 보여요.","운동을 하니 팔의 핏줄이 도드라졌어요."]),
        reference(292, "expansion-jeonsetdon", "saisiot", "exact", "expansion", "전셋돈 / 전세돈", "전셋돈", "전세를 얻을 때 맡기는 돈을 뜻해요. 이 말은 사이시옷을 살려 ‘전셋돈’로 적어요.", ["부모님은 전셋돈을 차곡차곡 모으셨어요.","전셋돈을 안전하게 돌려받았어요."]),
        reference(293, "expansion-hunnal", "saisiot", "exact", "expansion", "훗날 / 후날", "훗날", "시간이 지나 뒤에 오는 날을 뜻해요. 이 말은 사이시옷을 살려 ‘훗날’로 적어요.", ["훗날 다시 만나기로 약속했어요.","이 경험은 훗날 큰 도움이 될 거예요."]),
        reference(294, "expansion-namutgaji", "saisiot", "exact", "expansion", "나뭇가지 / 나무가지", "나뭇가지", "나무의 줄기에서 뻗은 가지를 뜻해요. 이 말은 사이시옷을 살려 ‘나뭇가지’로 적어요.", ["나뭇가지에 새가 앉았어요.","마른 나뭇가지가 바람에 흔들렸어요."]),
        reference(295, "expansion-meoritgireum", "saisiot", "exact", "expansion", "머릿기름 / 머리기름", "머릿기름", "머리에 바르는 기름을 뜻해요. 이 말은 사이시옷을 살려 ‘머릿기름’로 적어요.", ["할아버지는 머릿기름을 조금 바르셨어요.","머릿기름 향기가 은은했어요."]),
        reference(296, "expansion-araetjip", "saisiot", "exact", "expansion", "아랫집 / 아래집", "아랫집", "아래쪽에 있는 집을 뜻해요. 이 말은 사이시옷을 살려 ‘아랫집’로 적어요.", ["아랫집에 새 이웃이 이사 왔어요.","아랫집 친구와 함께 학교에 갔어요."]),
        reference(297, "expansion-yangchitmul", "saisiot", "exact", "expansion", "양칫물 / 양치물", "양칫물", "양치할 때 쓰는 물을 뜻해요. 이 말은 사이시옷을 살려 ‘양칫물’로 적어요.", ["양칫물을 컵에 받았어요.","양칫물을 함부로 흘리지 않아요."]),
        reference(298, "expansion-begaennit", "saisiot", "exact", "expansion", "베갯잇 / 베개잇", "베갯잇", "베개에 씌우는 천을 뜻해요. 이 말은 사이시옷을 살려 ‘베갯잇’로 적어요.", ["깨끗한 베갯잇으로 갈았어요.","베갯잇을 빨아 햇볕에 말렸어요."]),
        reference(299, "expansion-araetbang", "saisiot", "exact", "expansion", "아랫방 / 아래방", "아랫방", "아래쪽에 있는 방을 뜻해요. 이 말은 사이시옷을 살려 ‘아랫방’로 적어요.", ["아랫방에서 할머니가 쉬고 계세요.","아랫방 창문을 열어 환기했어요."]),
        reference(300, "expansion-dwinmal", "saisiot", "exact", "expansion", "뒷말 / 뒤말", "뒷말", "일이 끝난 뒤에 나오는 말이나 뒤에 있는 말을 뜻해요. 이 말은 사이시옷을 살려 ‘뒷말’로 적어요.", ["친구에 대한 뒷말을 하지 않아요.","앞말과 뒷말이 잘 이어져요."])
    ]
);
