export const weatherWidgetManifest = Object.freeze({
  id: 'weather',
  name: '날씨',
  description: '오늘과 내일 날씨를 골라 교실 안내와 함께 크게 보여 줘요',
  icon: '🌤️',
  version: 1,
  type: 'live-once',
  projectorSafe: true,
  maxInstances: 1,
  requestBudget: { initial: 1, refreshMs: null, realtime: false, maxRows: 5 },
  defaultPlacement: {
    zone: 'content',
    size: 'medium',
    placement: { x: 2.1, y: 50, width: 21, height: 32, pinned: false },
  },
  createDefaultConfig: () => ({
    weatherSource: 'live',
    locationName: '',
    latitude: null,
    longitude: null,
    message: '오늘도 즐겁게 시작해요!',
    days: ['today', 'tomorrow'],
  }),
  load: () => import('./WeatherWidget'),
  loadSettings: () => import('./WeatherSettings'),
});
