import { defineSpellingEntries, practice, reference } from './schema.js';

export const CONJUGATION_SPELLING_ENTRIES = defineSpellingEntries(
    'conjugation',
[
        reference(1, "dwae-doe", "doe-dwae", "exact", "base", "돼요 / 되요", "돼요", "‘돼’는 ‘되어’가 줄어든 말이에요. ‘되어요’라고 바꾸어 말할 수 있으면 ‘돼요’를 써요.", ["이제 집에 가도 돼요.","그렇게 하면 안 돼요."], {"searchable":["돼요","되요","돼","되","되어요","안 돼","해도 돼"],"sourceQuery":"되다"}),
        reference(10, "bwaeyo", "inflection", "exact", "base", "봬요 / 뵈요", "봬요", "‘뵈어요’가 줄어들면 ‘봬요’가 돼요. 줄이지 않으면 ‘뵈어요’라고 써요.", ["선생님, 내일 봬요.","다음에 다시 뵈어요."], {"searchable":["봬요","뵈요","뵈어요","내일 봬요"],"sourceQuery":"뵈다"}),
        reference(85, "dwaetda", "doe-dwae", "exact", "catalog", "됐다 / 됬다", "됐다", "‘되었다’가 줄어들면 ‘됐다’가 돼요.", ["준비가 모두 됐다.","계획대로 발표 준비가 됐다."], {"sourceQuery":"되다"}),
        reference(86, "watda", "contraction", "exact", "catalog", "왔다 / 왓다", "왔다", "‘오다’의 과거형은 ‘왔다’처럼 ‘ㅆ’을 받침으로 적어요.", ["친구가 우리 집에 왔다.","봄이 다시 왔다."], {"sourceQuery":"오다"}),
        reference(87, "gatda", "contraction", "exact", "catalog", "갔다 / 갓다", "갔다", "‘가다’의 과거형은 ‘갔다’라고 적어요.", ["어제 박물관에 갔다.","동생이 학교에 갔다."], {"sourceQuery":"가다"}),
        reference(88, "haetda", "contraction", "exact", "catalog", "했다 / 햇다", "했다", "‘하다’의 과거형은 ‘했다’라고 적어요.", ["숙제를 모두 했다.","친구와 함께 발표를 했다."], {"sourceQuery":"하다"}),
        reference(89, "bwatda", "contraction", "exact", "catalog", "봤다 / 봣다", "봤다", "‘보았다’가 줄어들면 ‘봤다’라고 적어요.", ["재미있는 영화를 봤다.","창밖의 무지개를 봤다."], {"sourceQuery":"보다"}),
        reference(90, "jwotda", "contraction", "exact", "catalog", "줬다 / 줫다", "줬다", "‘주었다’가 줄어들면 ‘줬다’라고 적어요.", ["친구가 연필을 빌려 줬다.","동생에게 사과를 나누어 줬다."], {"sourceQuery":"주다"}),
        reference(91, "doelge", "doe-dwae", "exact", "catalog", "될게 / 됄게", "될게", "‘되다’ 뒤에 ‘-ㄹ게’가 붙으면 ‘될게’가 돼요.", ["나는 훌륭한 사람이 될게.","다음에는 더 좋은 친구가 될게."], {"sourceQuery":"되다"}),
        reference(93, "boepgetseumnida", "contraction", "exact", "catalog", "뵙겠습니다 / 봽겠습니다", "뵙겠습니다", "‘뵙다’에 ‘-겠습니다’가 붙으면 ‘뵙겠습니다’라고 적어요.", ["내일 다시 뵙겠습니다.","행사장에서 선생님을 뵙겠습니다."], {"sourceQuery":"뵙다"}),
        reference(94, "bwoetda", "contraction", "exact", "catalog", "뵀다 / 봽다", "뵀다", "‘뵈었다’가 줄어들면 ‘뵀다’라고 적어요.", ["어제 선생님을 뵀다.","오랜만에 할머니를 뵀다."], {"sourceQuery":"뵈다"}),
        reference(95, "damgatda", "inflection", "exact", "catalog", "담갔다 / 담궜다", "담갔다", "‘담그다’의 과거형은 ‘담갔다’예요.", ["김치를 항아리에 담갔다.","손을 차가운 물에 담갔다."], {"sourceQuery":"담그다"}),
        reference(96, "jamgatda", "inflection", "exact", "catalog", "잠갔다 / 잠궜다", "잠갔다", "‘잠그다’의 과거형은 ‘잠갔다’예요.", ["문을 꼭 잠갔다.","수도꼭지를 잠갔다."], {"sourceQuery":"잠그다"}),
        reference(97, "chireotda", "inflection", "exact", "catalog", "치렀다 / 치뤘다", "치렀다", "시험이나 행사를 마쳤다는 뜻의 ‘치르다’는 ‘치렀다’로 활용해요.", ["오늘 시험을 치렀다.","학교에서 운동회를 치렀다."], {"sourceQuery":"치르다"}),
        reference(109, "dathida", "inflection", "exact", "catalog", "닫히다 / 닫치다", "닫히다", "‘닫다’의 피동 표현은 ‘닫히다’라고 적어요.", ["바람에 문이 저절로 닫혔어요.","엘리베이터 문이 닫히고 있어요."]),
        reference(113, "geonneotda", "inflection", "exact", "catalog", "건넜다 / 건넛다", "건넜다", "‘건너다’의 과거형은 ‘건넜다’라고 적어요.", ["횡단보도를 안전하게 건넜다.","징검다리를 조심히 건넜다."], {"sourceQuery":"건너다"}),
        reference(114, "seolletda", "contraction", "exact", "catalog", "설렜다 / 설레였다", "설렜다", "‘설레었다’가 줄어들면 ‘설렜다’가 돼요.", ["소풍 전날 마음이 설렜다.","새 친구를 만날 생각에 설렜다."], {"sourceQuery":"설레다"}),
        reference(301, "expansion-gatchuda", "inflection", "exact", "expansion", "갖추다 / 가추다", "갖추다", "필요한 것을 빠짐없이 마련한다는 뜻이에요. ‘가추다’가 아니라 ‘갖추다’로 적어요.", ["준비물을 모두 갖추었어요.","안전 장비를 갖추고 출발했어요."]),
        reference(302, "expansion-kkeokda", "inflection", "exact", "expansion", "꺾다 / 꺽다", "꺾다", "휘어서 구부리거나 경기에서 이긴다는 뜻이에요. ‘꺽다’가 아니라 ‘꺾다’로 적어요.", ["꽃가지를 함부로 꺾지 않아요.","우리 팀이 상대 팀을 꺾었어요."]),
        reference(303, "expansion-geodeobutida", "inflection", "exact", "expansion", "걷어붙이다 / 걷어부치다", "걷어붙이다", "소매나 바짓가랑이를 걷어서 붙여 놓는다는 뜻이에요. ‘걷어부치다’가 아니라 ‘걷어붙이다’로 적어요.", ["소매를 걷어붙이고 청소했어요.","바지를 걷어붙이고 개울을 건넜어요."]),
        reference(304, "expansion-gyeotdeurida", "inflection", "exact", "expansion", "곁들이다 / 곁드리다", "곁들이다", "주된 것에 다른 것을 함께 더한다는 뜻이에요. ‘곁드리다’가 아니라 ‘곁들이다’로 적어요.", ["빵에 우유를 곁들여 먹었어요.","발표에 그림을 곁들였어요."]),
        reference(305, "expansion-natchuda", "inflection", "exact", "expansion", "낮추다 / 낮히다", "낮추다", "높이거나 크던 것을 낮게 만든다는 뜻이에요. ‘낮히다’가 아니라 ‘낮추다’로 적어요.", ["목소리를 조금 낮추어 말했어요.","의자의 높이를 낮추었어요."]),
        reference(306, "expansion-nopida", "passive-causative", "exact", "expansion", "높이다 / 높히다", "높이다", "높게 하거나 정도를 크게 만든다는 뜻이에요. ‘높히다’가 아니라 ‘높이다’로 적어요.", ["상자의 높이를 높였어요.","집중력을 높이는 연습을 했어요."]),
        reference(307, "expansion-deopida", "passive-causative", "exact", "expansion", "덮이다 / 덮히다", "덮이다", "무엇이 위를 가리게 된다는 뜻이에요. ‘덮히다’가 아니라 ‘덮이다’로 적어요.", ["산이 흰 눈으로 덮였어요.","하늘이 먹구름에 덮였어요."]),
        reference(308, "expansion-doenoeda", "inflection", "exact", "expansion", "되뇌다 / 되내다", "되뇌다", "같은 말을 되풀이해 말한다는 뜻이에요. ‘되내다’가 아니라 ‘되뇌다’로 적어요.", ["중요한 문장을 속으로 되뇌었어요.","약속을 여러 번 되뇌며 기억했어요."]),
        reference(309, "expansion-matdaktteurida", "inflection", "exact", "expansion", "맞닥뜨리다 / 맞닥트리다", "맞닥뜨리다", "갑자기 마주 대하거나 어떤 일을 만난다는 뜻이에요. ‘맞닥트리다’가 아니라 ‘맞닥뜨리다’로 적어요.", ["길에서 친구와 맞닥뜨렸어요.","어려운 문제에 맞닥뜨려도 포기하지 않아요."]),
        reference(310, "expansion-meomureuda", "inflection", "exact", "expansion", "머무르다 / 머물르다", "머무르다", "한곳에 계속 있거나 어떤 상태가 이어진다는 뜻이에요. ‘머물르다’가 아니라 ‘머무르다’로 적어요.", ["도서관에 한 시간 머물렀어요.","구름이 산 위에 오래 머물렀어요."]),
        reference(311, "expansion-mireobutida", "inflection", "exact", "expansion", "밀어붙이다 / 밀어부치다", "밀어붙이다", "한쪽으로 세게 밀거나 일을 힘껏 진행한다는 뜻이에요. ‘밀어부치다’가 아니라 ‘밀어붙이다’로 적어요.", ["문을 끝까지 밀어붙였어요.","계획을 무리하게 밀어붙이지 않아요."]),
        reference(312, "expansion-muthida", "inflection", "exact", "expansion", "묻히다 / 뭍히다", "묻히다", "가루나 액체가 겉에 붙게 한다는 뜻이에요. ‘뭍히다’가 아니라 ‘묻히다’로 적어요.", ["빵에 설탕을 묻혔어요.","옷에 물감을 묻히지 않게 조심했어요."]),
        reference(313, "expansion-bepulda", "inflection", "exact", "expansion", "베풀다 / 배풀다", "베풀다", "남에게 도움이나 친절을 준다는 뜻이에요. ‘배풀다’가 아니라 ‘베풀다’로 적어요.", ["어려운 이웃에게 친절을 베풀었어요.","친구가 따뜻한 배려를 베풀었어요."]),
        reference(314, "expansion-sagwieotda", "inflection", "exact", "expansion", "사귀었다 / 사궜다", "사귀었다", "‘사귀다’의 과거형은 줄이지 않고 적어요. ‘사궜다’가 아니라 ‘사귀었다’로 적어요.", ["새 학기에도 많은 친구를 사귀었어요.","여행에서 만난 친구와 오래 사귀었어요."]),
        reference(315, "expansion-umcheurida", "inflection", "exact", "expansion", "움츠리다 / 움추리다", "움츠리다", "몸이나 몸의 일부를 작게 오므린다는 뜻이에요. ‘움추리다’가 아니라 ‘움츠리다’로 적어요.", ["추워서 어깨를 움츠렸어요.","거북이가 목을 움츠렸어요."]),
        reference(316, "expansion-ireukida", "passive-causative", "exact", "expansion", "일으키다 / 이르키다", "일으키다", "누운 것을 일어나게 하거나 일이 생기게 한다는 뜻이에요. ‘이르키다’가 아니라 ‘일으키다’로 적어요.", ["넘어진 자전거를 일으켰어요.","작은 실수가 큰 문제를 일으켰어요."]),
        reference(317, "expansion-jieotda", "inflection", "exact", "expansion", "지었다 / 짓었다", "지었다", "‘짓다’의 과거형은 ‘지었다’예요. ‘짓었다’가 아니라 ‘지었다’로 적어요.", ["동생에게 밝은 미소를 지었어요.","우리 가족은 작은 집을 지었어요."]),
        reference(318, "expansion-dwideopida", "passive-causative", "exact", "expansion", "뒤덮이다 / 뒤덮히다", "뒤덮이다", "빈 곳 없이 온통 덮이게 된다는 뜻이에요. ‘뒤덮히다’가 아니라 ‘뒤덮이다’로 적어요.", ["마을이 하얀 눈으로 뒤덮였어요.","운동장이 낙엽으로 뒤덮였어요."]),
        reference(319, "expansion-hearida", "inflection", "exact", "expansion", "헤아리다 / 해아리다", "헤아리다", "수나 마음을 짐작하여 생각한다는 뜻이에요. ‘해아리다’가 아니라 ‘헤아리다’로 적어요.", ["친구의 마음을 헤아려 보았어요.","별의 수를 헤아리기 어려웠어요."]),
        reference(320, "expansion-geoseureuda", "inflection", "exact", "expansion", "거스르다 / 거슬르다", "거스르다", "흐름이나 뜻을 따르지 않고 반대로 한다는 뜻이에요. ‘거슬르다’가 아니라 ‘거스르다’로 적어요.", ["물살을 거슬러 헤엄쳤어요.","자연의 흐름을 거스르지 않아요."]),
        reference(321, "expansion-ttareuda", "inflection", "exact", "expansion", "따르다 / 딸르다", "따르다", "다른 사람의 뒤를 좇거나 기준대로 한다는 뜻이에요. ‘딸르다’가 아니라 ‘따르다’로 적어요.", ["안내를 잘 따라 이동했어요.","모두 규칙을 따르기로 했어요."]),
        reference(322, "expansion-bureuda", "inflection", "exact", "expansion", "부르다 / 불르다", "부르다", "이름을 말해 오게 하거나 노래한다는 뜻이에요. ‘불르다’가 아니라 ‘부르다’로 적어요.", ["친구의 이름을 크게 불렀어요.","함께 동요를 불렀어요."]),
        reference(323, "expansion-goreuda", "inflection", "exact", "expansion", "고르다 / 골르다", "고르다", "여럿 가운데 하나를 선택한다는 뜻이에요. ‘골르다’가 아니라 ‘고르다’로 적어요.", ["마음에 드는 색을 골랐어요.","읽고 싶은 책을 한 권 고르세요."]),
        reference(324, "expansion-nureuda", "inflection", "exact", "expansion", "누르다 / 눌르다", "누르다", "위에서 아래로 힘을 준다는 뜻이에요. ‘눌르다’가 아니라 ‘누르다’로 적어요.", ["승강기 단추를 눌렀어요.","도장을 종이에 꾹 눌렀어요."]),
        reference(325, "expansion-gireuda", "inflection", "exact", "expansion", "기르다 / 길르다", "기르다", "생물이나 능력을 자라게 한다는 뜻이에요. ‘길르다’가 아니라 ‘기르다’로 적어요.", ["화분에 토마토를 길렀어요.","매일 읽으며 생각하는 힘을 길러요."]),
        reference(326, "expansion-jareuda", "inflection", "exact", "expansion", "자르다 / 잘르다", "자르다", "칼이나 가위로 끊어 낸다는 뜻이에요. ‘잘르다’가 아니라 ‘자르다’로 적어요.", ["가위로 종이를 잘랐어요.","색 테이프를 알맞게 자르세요."]),
        reference(327, "expansion-garaanjda", "inflection", "exact", "expansion", "가라앉다 / 가라안다", "가라앉다", "액체 아래로 내려가거나 마음이 조용해진다는 뜻이에요. ‘가라안다’가 아니라 ‘가라앉다’로 적어요.", ["물속의 모래가 천천히 가라앉았어요.","숨을 고르니 놀란 마음이 가라앉았어요."]),
        reference(328, "expansion-ppareuda", "inflection", "exact", "expansion", "빠르다 / 빨르다", "빠르다", "움직임이나 시간이 걸리는 정도가 짧다는 뜻이에요. ‘빨르다’가 아니라 ‘빠르다’로 적어요.", ["토끼는 거북이보다 빨라요.","아침에는 시간이 빠르게 흘러요."]),
        reference(329, "expansion-geeureuda", "inflection", "exact", "expansion", "게으르다 / 게을르다", "게으르다", "행동이 느리고 일을 하기 싫어하는 성질이 있다는 뜻이에요. ‘게을르다’가 아니라 ‘게으르다’로 적어요.", ["게으르지 않게 부지런히 움직였어요.","할 일을 미루면 점점 게을러져요."]),
        reference(330, "expansion-bullida", "passive-causative", "exact", "expansion", "불리다 / 불리우다", "불리다", "‘부르다’의 피동형은 ‘불리다’예요. ‘불리우다’가 아니라 ‘불리다’로 적어요.", ["그 아이는 반에서 박사라고 불렸어요.","이 꽃은 봄의 전령이라고 불려요."]),
        practice(401, "practice-spelling-quiz-001", "doe-dwae", "context", "이제 집에 가도 (되 / 돼).", "돼", "‘되어’로 바꿀 수 있으면 ‘돼’를 써요."),
        practice(402, "practice-spelling-quiz-002", "doe-dwae", "context", "나는 훌륭한 사람이 (될 / 됄) 거야.", "될", "‘됄’이라는 표현은 없어요."),
        practice(404, "practice-spelling-quiz-004", "doe-dwae", "context", "준비가 다 (됬어 / 됐어).", "됐어", "‘되었어’가 줄면 ‘됐어’가 돼요."),
        practice(456, "practice-spelling-quiz-056", "inflection", "context", "오늘 학교에서 시험을 (치뤘다 / 치렀다).", "치렀다", "기본형은 ‘치르다’예요."),
        practice(457, "practice-spelling-quiz-057", "inflection", "context", "어머니께서 김치를 (담궜다 / 담갔다).", "담갔다", "‘담그다’의 과거형은 ‘담갔다’예요."),
        practice(458, "practice-spelling-quiz-058", "inflection", "context", "외출하기 전에 문을 (잠궜다 / 잠갔다).", "잠갔다", "‘잠그다’의 과거형은 ‘잠갔다’예요."),
        practice(459, "practice-spelling-quiz-059", "inflection", "context", "전시된 물건을 함부로 (건들지 / 건드리지) 마세요.", "건드리지", "기본형은 ‘건드리다’예요."),
        practice(461, "practice-spelling-quiz-061", "inflection", "context", "네가 건강하기를 (바래 / 바라).", "바라", "무엇을 원한다는 뜻의 기본형은 ‘바라다’예요.")
    ]
);
