import { defineSpellingEntries, practice, reference } from './schema.js';

export const GRAMMAR_SPELLING_ENTRIES = defineSpellingEntries(
    'grammar',
[
        reference(11, "anieyo", "ending", "exact", "base", "아니에요 / 아니예요", "아니에요", "‘아니다’ 뒤에는 ‘-에요’가 붙어서 ‘아니에요’가 돼요.", ["제가 한 일이 아니에요.","그 연필은 제 것이 아니에요."], {"searchable":["아니에요","아니예요","이에요","예요"],"sourceQuery":"아니다"}),
        reference(12, "hal-su-itda", "dependent", "exact", "base", "할 수 있다 / 할수있다", "할 수 있다", "가능함을 나타내는 ‘수’는 앞말과 뒤의 ‘있다’에서 띄어 써요.", ["나는 끝까지 해낼 수 있어요.","여기에서 별을 볼 수 있어요."], {"searchable":["할 수 있다","할수있다","할수 있어","갈 수 있다","볼 수 있다"],"sourceType":"norm"}),
        reference(13, "geot-gatda", "dependent", "exact", "base", "것 같다 / 것같다", "것 같다", "‘것’은 앞말과 띄고, ‘같다’도 ‘것’과 띄어서 적어요.", ["곧 비가 올 것 같아요.","내 생각이 맞는 것 같아요."], {"searchable":["것 같다","것같다","거 같다","할 것 같다"],"sourceType":"norm"}),
        reference(20, "han-beon", "dependent", "context", "base", "한 번 / 한번", "뜻에 따라 달라요", "횟수 ‘한 차례’를 세면 ‘한 번’으로 띄어요. 시험 삼아 해 본다는 뜻이 강하면 ‘한번’으로 붙여 쓸 수 있어요.", ["딱 한 번만 더 읽어 볼게요.","이 문제를 한번 풀어 보세요."], {"searchable":["한 번","한번","한번 해 보다","한 번만"],"detectionPatterns":[{"text":"한번만","target":"한번","right":"한 번","lookup":"한 번"}],"sourceQuery":"한번"}),
        reference(21, "de-dae", "ending", "context", "base", "데 / 대", "뜻이 달라요", "장소나 경우를 나타내는 ‘데’가 있고, 다른 사람에게 들은 말을 전할 때 쓰는 ‘-대’가 있어요.", ["오늘은 갈 데가 없어요.","민지가 내일 학교에 온대요."], {"searchable":["데","대","갈 데","간대","했대","하는데"],"detectionPatterns":[{"text":"전학을 간데","target":"데","right":"대","lookup":"대"},{"text":"맛있데","target":"데","right":"대","lookup":"대"},{"text":"가 봤는대","target":"대","right":"데","lookup":"데"},{"text":"숙제하는 대","target":"대","right":"데","lookup":"데"}],"sourceQuery":"데"}),
        reference(23, "roseo-rosseo", "particle", "context", "base", "로서 / 로써", "뜻이 달라요", "자격이나 역할을 나타내면 ‘로서’, 도구나 방법을 나타내면 ‘로써’를 써요.", ["학생으로서 약속을 지켰어요.","대화로써 오해를 풀었어요."], {"searchable":["로서","로써","학생으로서","연필로써"],"detectionPatterns":[{"text":"학생으로써","target":"으로써","right":"으로서","lookup":"으로서"},{"text":"연필로서","target":"로서","right":"로써","lookup":"로써"}],"sourceType":"norm"}),
        reference(92, "halge", "ending", "exact", "catalog", "할게 / 할께", "할게", "약속이나 의지를 나타내는 어미는 ‘-ㄹ게’로 적어요.", ["내가 먼저 할게.","내일 꼭 돌려줄게."], {"sourceQuery":"-ㄹ게"}),
        reference(129, "deon-deun", "ending", "context", "catalog", "-던 / -든", "뜻에 따라 달라요", "지난 일을 떠올릴 때는 ‘-던’, 어느 것을 골라도 된다는 뜻에는 ‘-든’을 써요.", ["우리가 자주 놀던 공원이에요.","사과든 배든 하나를 골라요."], {"detectionPatterns":[{"text":"사과던 배던","target":"던","right":"든","lookup":"든"},{"text":"어제 먹었든","target":"든","right":"던","lookup":"던"},{"text":"어디에 가던 연락","target":"던","right":"든","lookup":"든"}],"sourceQuery":"-던"}),
        reference(130, "eyo-yeyo", "ending", "context", "catalog", "에요 / 예요", "받침에 따라 달라요", "받침 없는 말 뒤에는 ‘예요’, 받침 있는 말 뒤에는 ‘이에요’를 써요. ‘아니다’는 ‘아니에요’예요.", ["저는 민지예요.","이것은 연필이에요."], {"detectionPatterns":[{"text":"제 책에요","target":"에요","right":"이에요","lookup":"이에요"},{"text":"민수에요","target":"에요","right":"예요","lookup":"예요"},{"text":"선생님이예요","target":"이예요","right":"이에요","lookup":"이에요"},{"text":"거에요","target":"거에요","right":"거예요","lookup":"거예요"}],"sourceQuery":"-예요"}),
        reference(145, "an-hada", "negation", "exact", "catalog", "안 하다 / 안하다", "안 하다", "부정의 뜻을 더하는 ‘안’은 뒤의 동사와 띄어 써요.", ["오늘은 운동을 안 했어요.","약속을 잊지 않으려고 거짓말을 안 해요."], {"sourceType":"norm"}),
        reference(146, "mot-hada", "negation", "context", "catalog", "못 하다 / 못하다", "뜻에 따라 달라요", "어떤 행동을 하지 못했다면 띄어 쓰고, 능력이 부족하다는 뜻의 ‘못하다’는 붙여 쓸 수 있어요.", ["비가 와서 축구를 못 했어요.","나는 아직 수영을 못해요."], {"detectionPatterns":[{"text":"비가 와서 축구를 못했","target":"못했","right":"못 했","lookup":"못 했"}],"sourceType":"norm"}),
        reference(147, "du-beon", "dependent", "exact", "catalog", "두 번 / 두번", "두 번", "횟수를 세는 단위 ‘번’은 앞말과 띄어 써요.", ["문제를 두 번 읽었어요.","줄넘기를 두 번 연습했어요."], {"sourceType":"norm"}),
        reference(148, "myeot-beon", "dependent", "exact", "catalog", "몇 번 / 몇번", "몇 번", "횟수를 묻는 ‘몇’과 단위 ‘번’은 띄어 써요.", ["몇 번 버스를 타야 하나요?","이 책을 몇 번 읽었어요?"], {"sourceType":"norm"}),
        reference(149, "hal-ttae", "dependent", "exact", "catalog", "할 때 / 할때", "할 때", "시간을 나타내는 의존 명사 ‘때’는 앞말과 띄어 써요.", ["공부할 때에는 집중해요.","길을 건널 때 좌우를 살펴요."], {"sourceType":"norm"}),
        reference(150, "gal-ttae", "dependent", "exact", "catalog", "갈 때 / 갈때", "갈 때", "시간을 나타내는 ‘때’는 앞의 꾸며 주는 말과 띄어 써요.", ["학교에 갈 때 우산을 챙겼어요.","집에 갈 때 친구에게 인사했어요."], {"sourceType":"norm"}),
        reference(151, "ji-anhda", "negation", "exact", "catalog", "지 않다 / 지않다", "지 않다", "부정 표현 ‘-지 않다’에서 ‘않다’는 앞말과 띄어 써요.", ["약속을 잊지 않았어요.","복도에서 뛰지 않아요."], {"sourceType":"norm"}),
        reference(152, "su-bakke", "particle", "phrase", "catalog", "수밖에 / 수 밖에", "수밖에", "의존 명사 ‘수’는 앞말과 띄고, 조사 ‘밖에’는 ‘수’에 붙여 써요.", ["지금 출발할 수밖에 없어요.","다시 해 볼 수밖에 없었어요."], {"sourceType":"norm"}),
        reference(153, "geot-ppunida", "particle", "phrase", "catalog", "것뿐이다 / 것 뿐이다", "것뿐이다", "조사 ‘뿐’과 ‘이다’는 앞의 ‘것’에 붙여 써요.", ["내가 가진 것은 연필 한 자루뿐이다.","지금 할 수 있는 것은 기다리는 것뿐이다."], {"sourceType":"norm"}),
        reference(154, "hal-ppun", "dependent", "exact", "catalog", "할 뿐 / 할뿐", "할 뿐", "의존 명사 ‘뿐’이 ‘다만 그러할 따름’의 뜻이면 앞말과 띄어 써요.", ["나는 맡은 일을 할 뿐이에요.","사실을 말했을 뿐이에요."], {"sourceType":"norm"}),
        reference(155, "aneun-mankeum", "dependent", "exact", "catalog", "아는 만큼 / 아는만큼", "아는 만큼", "정도나 한도를 나타내는 의존 명사 ‘만큼’은 앞말과 띄어 써요.", ["아는 만큼 설명해 보세요.","노력한 만큼 실력이 늘어요."], {"sourceType":"norm"}),
        reference(156, "meogeul-mankeum", "dependent", "exact", "catalog", "먹을 만큼 / 먹을만큼", "먹을 만큼", "정도를 나타내는 의존 명사 ‘만큼’은 앞말과 띄어 써요.", ["먹을 만큼만 음식을 담아요.","배부르게 먹을 만큼 충분했어요."], {"sourceType":"norm"}),
        reference(157, "aneun-cheokhada", "dependent", "exact", "catalog", "아는 척하다 / 아는척하다", "아는 척하다", "그런 행동을 하는 듯이 보인다는 ‘척하다’는 앞말과 띄어 써요.", ["모르면서 아는 척하지 않았어요.","친구를 못 본 척하지 마세요."], {"sourceType":"norm"}),
        reference(158, "bon-chehada", "dependent", "exact", "catalog", "본 체하다 / 본체하다", "본 체하다", "그렇게 행동한 듯이 꾸미는 ‘체하다’는 앞말과 띄어 써요.", ["편지를 못 본 체했어요.","모르는 체하지 말고 도와주세요."], {"sourceType":"norm"}),
        reference(159, "gal-ri", "dependent", "exact", "catalog", "갈 리가 / 갈리가", "갈 리가", "까닭이나 가능성을 뜻하는 의존 명사 ‘리’는 앞말과 띄어 써요.", ["친구가 약속을 잊을 리가 없어요.","이 답이 틀릴 리가 없다고 다시 확인했어요."], {"sourceType":"norm"}),
        reference(160, "hal-jul", "dependent", "exact", "catalog", "할 줄 / 할줄", "할 줄", "방법이나 능력을 나타내는 의존 명사 ‘줄’은 앞말과 띄어 써요.", ["나는 자전거를 탈 줄 알아요.","동생은 아직 신발 끈을 묶을 줄 몰라요."], {"sourceType":"norm"}),
        reference(161, "on-ji", "dependent", "exact", "catalog", "온 지 / 온지", "온 지", "지난 시간을 나타내는 의존 명사 ‘지’는 앞말과 띄어 써요.", ["이사 온 지 한 달이 되었어요.","비가 온 지 오래되지 않았어요."], {"sourceType":"norm"}),
        reference(162, "mannan-ji", "dependent", "exact", "catalog", "만난 지 / 만난지", "만난 지", "얼마나 시간이 지났는지를 나타내는 ‘지’는 앞말과 띄어 써요.", ["친구를 만난 지 일주일이 지났어요.","선생님을 만난 지 얼마 안 되었어요."], {"sourceType":"norm"}),
        reference(163, "se-sal", "dependent", "exact", "catalog", "세 살 / 세살", "세 살", "나이를 세는 단위 ‘살’은 앞의 수와 띄어 써요.", ["동생은 세 살이에요.","나는 세 살 때 처음 바다를 보았어요."], {"sourceType":"norm"}),
        reference(164, "yeol-sal", "dependent", "exact", "catalog", "열 살 / 열살", "열 살", "나이를 세는 단위 ‘살’은 앞말과 띄어 써요.", ["내년에 열 살이 돼요.","그 아이는 열 살이에요."], {"sourceType":"norm"}),
        reference(165, "han-myeong", "dependent", "exact", "catalog", "한 명 / 한명", "한 명", "사람을 세는 단위 ‘명’은 앞의 수와 띄어 써요.", ["학생 한 명이 발표했어요.","한 명씩 차례로 들어가요."], {"sourceType":"norm"}),
        reference(166, "du-mari", "dependent", "exact", "catalog", "두 마리 / 두마리", "두 마리", "동물을 세는 단위 ‘마리’는 앞의 수와 띄어 써요.", ["강아지 두 마리가 뛰어놀아요.","연못에서 오리 두 마리를 보았어요."], {"sourceType":"norm"}),
        reference(167, "cheot-beonjjae", "dependent", "exact", "catalog", "첫 번째 / 첫번째", "첫 번째", "차례를 나타내는 ‘번째’는 앞말과 띄어 써요.", ["첫 번째 문제를 풀었어요.","달리기에서 첫 번째로 들어왔어요."], {"sourceType":"norm"}),
        reference(168, "du-beonjjae", "dependent", "exact", "catalog", "두 번째 / 두번째", "두 번째", "차례를 나타내는 ‘번째’는 앞의 수와 띄어 써요.", ["두 번째 문장을 읽어 보세요.","오늘 두 번째 손님이 왔어요."], {"sourceType":"norm"}),
        reference(169, "i-saram", "spacing", "exact", "catalog", "이 사람 / 이사람", "이 사람", "사람을 가리키는 ‘이’와 명사 ‘사람’은 띄어 써요.", ["이 사람은 우리 선생님이에요.","이 사람이 길을 알려 주었어요."], {"sourceType":"norm"}),
        reference(170, "geu-saram", "spacing", "exact", "catalog", "그 사람 / 그사람", "그 사람", "사람을 가리키는 ‘그’와 명사 ‘사람’은 띄어 써요.", ["그 사람을 전에 만난 적이 있어요.","그 사람이 우산을 빌려주었어요."], {"sourceType":"norm"}),
        reference(171, "jeo-saram", "spacing", "exact", "catalog", "저 사람 / 저사람", "저 사람", "사람을 가리키는 ‘저’와 명사 ‘사람’은 띄어 써요.", ["저 사람은 누구인가요?","저 사람이 손을 흔들고 있어요."], {"sourceType":"norm"}),
        reference(172, "eoneu-nal", "spacing", "exact", "catalog", "어느 날 / 어느날", "어느 날", "정해지지 않은 날을 나타내는 ‘어느’와 ‘날’은 띄어 써요.", ["어느 날 작은 새가 찾아왔어요.","어느 날 꿈이 이루어질 거예요."], {"sourceType":"norm"}),
        reference(173, "eoneu-ttae", "spacing", "exact", "catalog", "어느 때 / 어느때", "어느 때", "정해지지 않은 시간을 나타내는 ‘어느’와 ‘때’는 띄어 써요.", ["어느 때가 가장 즐거웠나요?","어느 때든 서로 도와요."], {"sourceType":"norm"}),
        reference(174, "eolma-dongan", "dependent", "exact", "catalog", "얼마 동안 / 얼마동안", "얼마 동안", "시간의 길이를 나타내는 ‘얼마’와 ‘동안’은 띄어 써요.", ["얼마 동안 기다려야 하나요?","방학 동안 얼마 동안 여행했어요?"], {"sourceType":"norm"}),
        reference(175, "haru-jongil", "dependent", "exact", "catalog", "하루 종일 / 하루종일", "하루 종일", "아침부터 밤까지를 뜻하는 ‘하루 종일’은 띄어 써요.", ["하루 종일 비가 내렸어요.","하루 종일 책을 읽었어요."], {"sourceType":"norm"}),
        reference(176, "achimmada", "particle", "phrase", "catalog", "아침마다 / 아침 마다", "아침마다", "하나하나 빠짐없이 모두를 뜻하는 조사 ‘마다’는 앞말에 붙여 써요.", ["아침마다 스트레칭을 해요.","아침마다 새가 창가에 와요."], {"sourceType":"norm"}),
        reference(177, "nalmada", "particle", "phrase", "catalog", "날마다 / 날 마다", "날마다", "매일을 뜻하는 ‘마다’는 앞말에 붙여 써요.", ["날마다 일기를 써요.","날마다 조금씩 자라고 있어요."], {"sourceType":"norm"}),
        reference(178, "neobakke", "particle", "phrase", "catalog", "너밖에 / 너 밖에", "너밖에", "오직 그것뿐이라는 뜻의 조사 ‘밖에’는 앞말에 붙여 써요.", ["나를 도와줄 사람은 너밖에 없어.","이 사실을 아는 사람은 너밖에 없어요."], {"sourceType":"norm"}),
        reference(179, "nacheoreom", "particle", "phrase", "catalog", "나처럼 / 나 처럼", "나처럼", "비슷함을 나타내는 조사 ‘처럼’은 앞말에 붙여 써요.", ["나처럼 천천히 해 보세요.","동생도 나처럼 책을 좋아해요."], {"sourceType":"norm"}),
        reference(180, "chinguwa", "particle", "phrase", "catalog", "친구와 / 친구 와", "친구와", "함께하는 대상을 나타내는 조사 ‘와’는 앞말에 붙여 써요.", ["친구와 공원에 갔어요.","친구와 힘을 합쳐 완성했어요."], {"sourceType":"norm"}),
        reference(181, "hakgyokkaji", "particle", "phrase", "catalog", "학교까지 / 학교 까지", "학교까지", "범위의 끝을 나타내는 조사 ‘까지’는 앞말에 붙여 써요.", ["집에서 학교까지 걸어갔어요.","오늘은 세 쪽까지 읽어요."], {"sourceType":"norm"}),
        reference(182, "jibeseobuteo", "particle", "phrase", "catalog", "집에서부터 / 집에서 부터", "집에서부터", "시작점을 나타내는 조사 ‘부터’는 앞말에 붙여 써요.", ["집에서부터 학교까지 달렸어요.","첫 줄에서부터 다시 읽었어요."], {"sourceType":"norm"}),
        reference(183, "hal-ge", "ending", "context", "catalog", "할 게 / 할게", "뜻에 따라 달라요", "‘할 것이’가 줄면 ‘할 게’로 띄고, 약속의 어미 ‘-ㄹ게’는 붙여 써요.", ["오늘 할 게 많이 남았어요.","청소는 내가 할게."], {"detectionPatterns":[{"text":"할게 많이","target":"할게","right":"할 게","lookup":"할 게"},{"text":"청소는 내가 할 게.","target":"할 게","right":"할게","lookup":"할게"}],"sourceType":"norm"}),
        reference(184, "hal-geol", "ending", "context", "catalog", "할 걸 / 할걸", "뜻에 따라 달라요", "‘할 것을’이 줄면 ‘할 걸’로 띄고, 아쉬움이나 추측을 나타내는 어미 ‘-ㄹ걸’은 붙여 쓸 수 있어요.", ["지금 할 걸 먼저 골라 보세요.","조금 더 일찍 출발할걸."], {"detectionPatterns":[{"text":"할걸 먼저","target":"할걸","right":"할 걸","lookup":"할 걸"},{"text":"갈 걸 그랬다","target":"갈 걸","right":"갈걸","lookup":"갈걸"}],"sourceType":"norm"}),
        reference(331, "expansion-ibeon-ju", "spacing", "exact", "expansion", "이번 주 / 이번주", "이번 주", "‘이번’은 관형사이므로 뒤의 명사 ‘주’와 띄어 써요.", ["이번 주에는 체험 학습이 있어요.","이번 주 숙제를 모두 끝냈어요."], {"sourceType":"norm"}),
        reference(332, "expansion-daeum-ju", "spacing", "exact", "expansion", "다음 주 / 다음주", "다음 주", "뒤에 오는 주를 뜻하는 ‘다음 주’는 두 단어로 띄어 써요.", ["다음 주에 다시 만나요.","대회는 다음 주 토요일에 열려요."], {"sourceType":"norm"}),
        reference(333, "expansion-myeot-nyeon", "dependent", "exact", "expansion", "몇 년 / 몇년", "몇 년", "해의 수를 나타내는 단위 ‘년’은 앞말과 띄어 써요.", ["이 나무는 몇 년이나 자랐을까요?","몇 년 뒤에 다시 찾아왔어요."], {"sourceType":"norm"}),
        reference(334, "expansion-yeoreo-hae", "dependent", "exact", "expansion", "여러 해 / 여러해", "여러 해", "수량을 나타내는 ‘여러’와 명사 ‘해’는 띄어 써요.", ["여러 해 동안 나무를 관찰했어요.","여러 해가 지나 다시 만났어요."], {"sourceType":"norm"}),
        reference(335, "expansion-deo-isang", "spacing", "exact", "expansion", "더 이상 / 더이상", "더 이상", "‘더’와 ‘이상’은 각각 독립된 단어이므로 띄어 써요.", ["더 이상 걱정하지 않아도 돼요.","물이 더 이상 나오지 않았어요."], {"sourceType":"norm"}),
        reference(336, "expansion-maen-meonjeo", "spacing", "exact", "expansion", "맨 먼저 / 맨먼저", "맨 먼저", "가장 앞이라는 뜻의 ‘맨’은 뒤의 부사 ‘먼저’와 띄어 써요.", ["교실에 맨 먼저 도착했어요.","맨 먼저 손을 든 친구가 대답했어요."], {"sourceType":"norm"}),
        reference(337, "expansion-gajang-meonjeo", "spacing", "exact", "expansion", "가장 먼저 / 가장먼저", "가장 먼저", "정도가 으뜸임을 나타내는 ‘가장’과 ‘먼저’는 띄어 써요.", ["해야 할 일을 가장 먼저 정했어요.","가장 먼저 떠오른 생각을 적었어요."], {"sourceType":"norm"}),
        reference(338, "expansion-hal-gyehoek", "spacing", "exact", "expansion", "할 계획 / 할계획", "할 계획", "관형어 ‘할’과 명사 ‘계획’은 띄어 써요.", ["주말에 박물관을 구경할 계획이에요.","방학에 책을 많이 읽을 계획을 세웠어요."], {"sourceType":"norm"}),
        reference(339, "expansion-gal-yejeong", "spacing", "exact", "expansion", "갈 예정 / 갈예정", "갈 예정", "관형어 ‘갈’과 명사 ‘예정’은 띄어 써요.", ["내일 도서관에 갈 예정이에요.","이번 방학에는 제주도에 갈 예정이에요."], {"sourceType":"norm"}),
        reference(340, "expansion-hal-piryo", "spacing", "exact", "expansion", "할 필요 / 할필요", "할 필요", "관형어 ‘할’과 명사 ‘필요’는 띄어 써요.", ["서두를 필요는 없어요.","모두 함께 확인할 필요가 있어요."], {"sourceType":"norm"}),
        reference(341, "expansion-hagi-wihae", "spacing", "exact", "expansion", "하기 위해 / 하기위해", "하기 위해", "목적을 나타내는 ‘위해’는 앞의 ‘하기’와 띄어 써요.", ["건강해지기 위해 운동했어요.","약속을 지키기 위해 서둘렀어요."], {"sourceType":"norm"}),
        reference(342, "expansion-haneun-jung", "dependent", "exact", "expansion", "하는 중 / 하는중", "하는 중", "어떤 일이 진행되는 때를 나타내는 의존 명사 ‘중’은 앞말과 띄어 써요.", ["지금 숙제를 하는 중이에요.","친구와 이야기하는 중에 종이 울렸어요."], {"sourceType":"norm"}),
        reference(343, "expansion-sueop-jung", "dependent", "exact", "expansion", "수업 중 / 수업중", "수업 중", "어떤 활동이 진행되는 동안을 나타내는 ‘중’은 앞말과 띄어 써요.", ["수업 중에는 조용히 들어요.","수업 중에 궁금한 점을 적었어요."], {"sourceType":"norm"}),
        reference(344, "expansion-gongbu-jung", "dependent", "exact", "expansion", "공부 중 / 공부중", "공부 중", "어떤 활동이 진행되는 동안을 나타내는 ‘중’은 앞말과 띄어 써요.", ["동생은 지금 공부 중이에요.","공부 중에는 휴대 전화를 보지 않아요."], {"sourceType":"norm"}),
        reference(345, "expansion-sayong-jung", "dependent", "exact", "expansion", "사용 중 / 사용중", "사용 중", "무엇을 쓰고 있는 동안을 나타내는 ‘중’은 앞말과 띄어 써요.", ["이 컴퓨터는 지금 사용 중이에요.","사용 중인 물건을 함부로 가져가지 않아요."], {"sourceType":"norm"}),
        reference(346, "expansion-hoeui-jung", "dependent", "exact", "expansion", "회의 중 / 회의중", "회의 중", "회의가 진행되는 동안을 나타내는 ‘중’은 앞말과 띄어 써요.", ["선생님들은 지금 회의 중이세요.","회의 중에는 문을 조용히 닫아요."], {"sourceType":"norm"}),
        reference(347, "expansion-nae-geot", "dependent", "exact", "expansion", "내 것 / 내것", "내 것", "소유를 나타내는 관형어 ‘내’와 의존 명사 ‘것’은 띄어 써요.", ["이 공책은 내 것이에요.","내 것과 친구 것을 구별했어요."], {"sourceType":"norm"}),
        reference(348, "expansion-ne-geot", "dependent", "exact", "expansion", "네 것 / 네것", "네 것", "소유를 나타내는 관형어 ‘네’와 의존 명사 ‘것’은 띄어 써요.", ["책상 위 연필은 네 것이야.","네 것은 네가 잘 챙기세요."], {"sourceType":"norm"}),
        reference(349, "expansion-je-geot", "dependent", "exact", "expansion", "제 것 / 제것", "제 것", "소유를 나타내는 관형어 ‘제’와 의존 명사 ‘것’은 띄어 써요.", ["잃어버린 우산은 제 것이에요.","제 것은 제가 정리할게요."], {"sourceType":"norm"}),
        reference(350, "expansion-hal-geosinga", "dependent", "exact", "expansion", "할 것인가 / 할것인가", "할 것인가", "관형어 뒤의 의존 명사 ‘것’은 띄어 써요.", ["무엇을 먼저 할 것인가 생각했어요.","계속 도전할 것인가 물었어요."], {"sourceType":"norm"}),
        reference(351, "expansion-bon-jeogi-itda", "dependent", "phrase", "expansion", "본 적이 있다 / 본적이 있다", "본 적이 있다", "경험을 나타내는 의존 명사 ‘적’은 앞말과 띄어 써요.", ["무지개를 가까이에서 본 적이 있어요.","그 책을 전에 본 적이 있어요."], {"sourceType":"norm"}),
        reference(352, "expansion-gan-jeogi-itda", "dependent", "phrase", "expansion", "간 적이 있다 / 간적이 있다", "간 적이 있다", "경험을 나타내는 의존 명사 ‘적’은 앞말과 띄어 써요.", ["제주도에 간 적이 있어요.","가족과 캠핑을 간 적이 있어요."], {"sourceType":"norm"}),
        reference(353, "expansion-sseun-jeogi-eopda", "dependent", "phrase", "expansion", "쓴 적이 없다 / 쓴적이 없다", "쓴 적이 없다", "경험을 나타내는 의존 명사 ‘적’은 앞말과 띄어 써요.", ["나는 그 도구를 쓴 적이 없어요.","거짓말을 쓴 적이 없다고 말했어요."], {"sourceType":"norm"}),
        reference(354, "expansion-eoneusae", "joined-word", "phrase", "expansion", "어느새 / 어느 새", "어느새", "어느 틈에 벌써라는 뜻의 부사 ‘어느새’는 한 단어로 붙여 써요.", ["어느새 해가 저물었어요.","아기가 어느새 훌쩍 자랐어요."], {"sourceType":"norm"}),
        reference(355, "expansion-eoneudeot", "joined-word", "phrase", "expansion", "어느덧 / 어느 덧", "어느덧", "어느 사이인지 모르게라는 뜻의 ‘어느덧’은 붙여 써요.", ["어느덧 봄이 찾아왔어요.","이야기하다 보니 어느덧 밤이 되었어요."], {"sourceType":"norm"}),
        reference(356, "expansion-hankkeobeone", "joined-word", "phrase", "expansion", "한꺼번에 / 한 꺼번에", "한꺼번에", "몰아서 한 번에라는 뜻의 ‘한꺼번에’는 한 단어예요.", ["질문을 한꺼번에 하지 마세요.","상자를 한꺼번에 옮겼어요."], {"sourceType":"norm"}),
        reference(357, "expansion-onjongil", "joined-word", "phrase", "expansion", "온종일 / 온 종일", "온종일", "아침부터 저녁까지의 동안을 뜻하는 ‘온종일’은 한 단어예요.", ["온종일 비가 내렸어요.","고양이는 온종일 창가에서 잤어요."], {"sourceType":"norm"}),
        reference(358, "expansion-myeochiljjae", "affix", "phrase", "expansion", "며칠째 / 며칠 째", "며칠째", "차례나 동안을 나타내는 접미사 ‘-째’는 앞말에 붙여 써요.", ["비가 며칠째 내리고 있어요.","며칠째 같은 책을 읽고 있어요."], {"sourceType":"norm"}),
        reference(359, "expansion-cheonnal", "joined-word", "phrase", "expansion", "첫날 / 첫 날", "첫날", "어떤 기간이 시작되는 맨 처음 날은 ‘첫날’로 붙여 써요.", ["개학 첫날에 친구들을 만났어요.","여행 첫날부터 날씨가 좋았어요."], {"sourceType":"norm"}),
        reference(360, "expansion-hangaunde", "joined-word", "phrase", "expansion", "한가운데 / 한 가운데", "한가운데", "어떤 곳의 바로 가운데를 뜻하는 ‘한가운데’는 한 단어예요.", ["운동장 한가운데에 공이 놓였어요.","방 한가운데에 둥근 탁자가 있어요."], {"sourceType":"norm"}),
        reference(361, "expansion-jettae", "joined-word", "phrase", "expansion", "제때 / 제 때", "제때", "알맞은 때를 뜻하는 ‘제때’는 한 단어로 붙여 써요.", ["숙제를 제때 제출했어요.","밥을 제때 먹어야 건강해요."], {"sourceType":"norm"}),
        reference(362, "expansion-ittae", "joined-word", "phrase", "expansion", "이때 / 이 때", "이때", "바로 지금의 때를 뜻하는 ‘이때’는 한 단어예요.", ["이때 문이 갑자기 열렸어요.","이때를 놓치지 말고 출발해요."], {"sourceType":"norm"}),
        reference(363, "expansion-geuttae", "joined-word", "phrase", "expansion", "그때 / 그 때", "그때", "앞에서 말한 때를 가리키는 ‘그때’는 한 단어예요.", ["그때 만난 친구를 기억해요.","그때는 눈이 많이 내렸어요."], {"sourceType":"norm"}),
        reference(364, "expansion-geudongan", "joined-word", "phrase", "expansion", "그동안 / 그 동안", "그동안", "앞에서 말한 때부터 지금까지를 뜻하는 ‘그동안’은 한 단어예요.", ["그동안 어떻게 지냈나요?","그동안 연습한 실력을 보여 주었어요."], {"sourceType":"norm"}),
        reference(365, "expansion-handongan", "joined-word", "phrase", "expansion", "한동안 / 한 동안", "한동안", "꽤 오랫동안이라는 뜻의 ‘한동안’은 한 단어예요.", ["한동안 비가 오지 않았어요.","친구와 한동안 이야기를 나누었어요."], {"sourceType":"norm"}),
        reference(366, "expansion-hanbamjung", "joined-word", "phrase", "expansion", "한밤중 / 한 밤중", "한밤중", "깊은 밤을 뜻하는 ‘한밤중’은 한 단어로 붙여 써요.", ["한밤중에 천둥소리가 들렸어요.","한밤중에는 모두 잠들어 있었어요."], {"sourceType":"norm"}),
        reference(367, "expansion-galsurok", "ending", "phrase", "expansion", "갈수록 / 갈 수록", "갈수록", "정도가 점점 더해짐을 나타내는 어미 ‘-ㄹ수록’은 앞말에 붙여 써요.", ["날이 갈수록 따뜻해져요.","연습할수록 실력이 늘어요."], {"sourceType":"norm"}),
        reference(368, "expansion-halsurok", "ending", "phrase", "expansion", "할수록 / 할 수록", "할수록", "정도가 점점 더해짐을 나타내는 어미 ‘-ㄹ수록’은 앞말에 붙여 써요.", ["생각할수록 좋은 방법 같아요.","운동을 할수록 몸이 튼튼해져요."], {"sourceType":"norm"}),
        reference(369, "expansion-doelsurok", "ending", "phrase", "expansion", "될수록 / 될 수록", "될수록", "‘되다’에 붙는 어미 ‘-ㄹ수록’은 붙여 적어요.", ["어른이 될수록 책임도 커져요.","마감 시간이 될수록 마음이 바빠졌어요."], {"sourceType":"norm"}),
        reference(370, "expansion-myeochilgan", "affix", "phrase", "expansion", "며칠간 / 며칠 간", "며칠간", "기간을 나타내는 접미사 ‘-간’은 앞말에 붙여 써요.", ["며칠간 비가 계속 내렸어요.","며칠간 여행을 다녀왔어요."], {"sourceType":"norm"}),
        practice(403, "practice-spelling-quiz-003", "negation", "context", "그렇게 하면 (안되 / 안 돼).", "안 돼", "‘안’은 뒤의 ‘돼’와 띄어 써요."),
        practice(405, "practice-spelling-quiz-005", "ending", "context", "숙제를 다 하면 게임을 해도 (된데 / 된대).", "된대", "‘된다고 해’가 줄어든 말은 ‘된대’예요."),
        practice(406, "practice-spelling-quiz-006", "negation", "context", "오늘은 학교에 (안 / 않) 간다.", "안", "‘안’은 ‘아니’가 줄어든 말이에요."),
        practice(407, "practice-spelling-quiz-007", "negation", "context", "숙제를 하지 (안았다 / 않았다).", "않았다", "‘-지 않다’의 과거형은 ‘-지 않았다’예요."),
        practice(408, "practice-spelling-quiz-008", "negation", "context", "밥을 먹지 (안고 / 않고) 나왔다.", "않고", "‘-지 않고’가 바른 표현이에요."),
        practice(409, "practice-spelling-quiz-009", "negation", "context", "나는 매운 음식을 잘 먹지 (안는다 / 않는다).", "않는다", "‘-지 않는다’라고 써요."),
        practice(410, "practice-spelling-quiz-010", "negation", "context", "오늘은 숙제를 (안 했다 / 않았다).", "안 했다", "‘안 했다’로 쓰며 ‘하지 않았다’라고 바꿔 쓸 수도 있어요."),
        practice(467, "practice-spelling-quiz-067", "ending", "context", "친구가 내일 전학을 간(데 / 대).", "대", "‘간다고 해’가 줄면 ‘간대’가 돼요."),
        practice(468, "practice-spelling-quiz-068", "ending", "context", "동생이 이 과자가 맛있(데 / 대).", "대", "다른 사람에게 들은 말을 전할 때에는 ‘-대’를 써요."),
        practice(469, "practice-spelling-quiz-069", "ending", "context", "내가 어제 가 봤는(데 / 대) 정말 재미있었어.", "데", "직접 겪은 상황을 이어 말할 때에는 ‘-데’를 써요."),
        practice(470, "practice-spelling-quiz-070", "ending", "context", "숙제하는 (대 / 데) 한 시간이 걸렸다.", "데", "어떤 일이나 상황을 뜻하는 ‘데’를 써요."),
        practice(471, "practice-spelling-quiz-071", "ending", "phrase", "사과(든 / 던) 배(든 / 던) 하나 골라라.", "든, 든", "선택을 나타낼 때에는 ‘든’을 써요.", ["든, 든","던, 던"]),
        practice(472, "practice-spelling-quiz-072", "ending", "context", "내가 어제 먹었(든 / 던) 빵이다.", "던", "지난 일을 떠올릴 때에는 ‘-던’을 써요."),
        practice(473, "practice-spelling-quiz-073", "ending", "context", "어디에 가(든 / 던) 연락해 줘.", "든", "어느 것을 선택해도 된다는 뜻에는 ‘-든’을 써요."),
        practice(474, "practice-spelling-quiz-074", "ending", "context", "예전에 자주 놀(든 / 던) 놀이터다.", "던", "과거의 경험을 나타낼 때에는 ‘-던’을 써요."),
        practice(475, "practice-spelling-quiz-075", "dependent", "context", "모르는 (채 / 체)하고 지나갔다.", "체", "그런 척한다는 뜻에는 ‘체’를 써요."),
        practice(476, "practice-spelling-quiz-076", "dependent", "context", "신발을 신은 (체 / 채) 방에 들어왔다.", "채", "어떤 상태가 그대로 이어진다는 뜻에는 ‘채’를 써요."),
        practice(477, "practice-spelling-quiz-077", "dependent", "context", "자는 (채 / 체) 눈을 감고 있었다.", "체", "실제로 자지 않고 자는 척한다는 뜻에는 ‘체’를 써요."),
        practice(478, "practice-spelling-quiz-078", "dependent", "context", "가방을 멘 (체 / 채) 의자에 앉았다.", "채", "가방을 멘 상태가 계속된다는 뜻에는 ‘채’를 써요."),
        practice(479, "practice-spelling-quiz-079", "ending", "context", "이것은 제 책(에요 / 이에요).", "이에요", "받침 있는 말 뒤에는 ‘이에요’를 써요."),
        practice(480, "practice-spelling-quiz-080", "ending", "context", "저는 민수(에요 / 예요).", "예요", "받침 없는 말 뒤에는 ‘예요’를 써요."),
        practice(481, "practice-spelling-quiz-081", "ending", "context", "저 사람은 우리 선생님(이예요 / 이에요).", "이에요", "‘이예요’가 아니라 ‘이에요’라고 써요."),
        practice(482, "practice-spelling-quiz-082", "ending", "context", "내일 비가 올 (거에요 / 거예요).", "거예요", "‘것이에요’가 줄면 ‘거예요’가 돼요."),
        practice(483, "practice-spelling-quiz-083", "ending", "context", "내가 청소를 (할께 / 할게).", "할게", "약속이나 의지를 나타내는 어미는 ‘-ㄹ게’예요."),
        practice(484, "practice-spelling-quiz-084", "ending", "context", "조금 있다가 전화(할께 / 할게).", "할게", "‘-ㄹ께’가 아니라 ‘-ㄹ게’라고 써요."),
        practice(485, "practice-spelling-quiz-085", "ending", "context", "나도 같이 (갈께 / 갈게).", "갈게", "‘-ㄹ게’로 써요."),
        practice(486, "practice-spelling-quiz-086", "ending", "context", "그때 같이 (갈껄 / 갈걸) 그랬다.", "갈걸", "아쉬움을 나타내는 어미는 ‘-ㄹ걸’이에요."),
        practice(487, "practice-spelling-quiz-087", "ending", "context", "나도 한 번 해 (볼껄 / 볼걸).", "볼걸", "어미 ‘-ㄹ걸’은 된소리로 적지 않아요."),
        practice(488, "practice-spelling-quiz-088", "dependent", "context", "나는 혼자서도 (할수 있다 / 할 수 있다).", "할 수 있다", "의존 명사 ‘수’는 앞말과 띄어 써요."),
        practice(489, "practice-spelling-quiz-089", "dependent", "context", "내일 도서관에 (갈것이다 / 갈 것이다).", "갈 것이다", "의존 명사 ‘것’은 앞말과 띄어 써요."),
        practice(490, "practice-spelling-quiz-090", "dependent", "context", "사과를 (한개 / 한 개) 먹었다.", "한 개", "단위를 나타내는 ‘개’는 앞말과 띄어 써요."),
        practice(491, "practice-spelling-quiz-091", "dependent", "context", "운동장에 학생 (세명 / 세 명)이 있다.", "세 명", "사람을 세는 ‘명’은 앞말과 띄어 써요."),
        practice(492, "practice-spelling-quiz-092", "dependent", "context", "물을 (두잔 / 두 잔) 마셨다.", "두 잔", "단위를 나타내는 ‘잔’은 앞말과 띄어 써요."),
        practice(493, "practice-spelling-quiz-093", "dependent", "context", "나도 (한번 / 한 번) 해 보고 싶다.", "한 번", "횟수를 나타낼 때에는 ‘한 번’으로 띄어 써요."),
        practice(494, "practice-spelling-quiz-094", "particle", "context", "밥을 먹은 (후에 / 후 에) 운동했다.", "후에", "조사 ‘에’는 앞말에 붙여 써요."),
        practice(495, "practice-spelling-quiz-095", "dependent", "context", "곧 비가 올 (것같다 / 것 같다).", "것 같다", "‘것’은 앞말과 띄어 써요."),
        practice(496, "practice-spelling-quiz-096", "dependent", "context", "숙제를 다 (한후 / 한 후) 놀았다.", "한 후", "‘후’는 앞말과 띄어 써요."),
        practice(497, "practice-spelling-quiz-097", "dependent", "context", "집에 (갈때 / 갈 때) 비가 왔다.", "갈 때", "‘때’는 앞말과 띄어 써요."),
        practice(498, "practice-spelling-quiz-098", "dependent", "context", "밥을 (먹은뒤 / 먹은 뒤) 이를 닦았다.", "먹은 뒤", "‘뒤’는 앞말과 띄어 써요."),
        practice(499, "practice-spelling-quiz-099", "dependent", "context", "아는 (대로 / 데로) 설명해 봐.", "대로", "‘어떤 모양이나 상태와 같이’라는 뜻에는 ‘대로’를 써요."),
        practice(500, "practice-spelling-quiz-100", "dependent", "context", "선생님 말씀(데로 / 대로) 따라 했다.", "대로", "‘데로’가 아니라 조사 ‘대로’를 앞말에 붙여 써요.")
    ]
);
