import { defineSpellingEntries, reference } from './schema.js';

export const LOANWORD_SPELLING_ENTRIES = defineSpellingEntries(
    'loanword',
[
        reference(185, "cake", "loanword", "exact", "catalog", "케이크 / 케익", "케이크", "영어 cake를 한글로 적을 때에는 ‘케이크’라고 적어요.", ["생일 케이크의 촛불을 껐어요.","친구와 케이크를 나누어 먹었어요."]),
        reference(186, "chocolate", "loanword", "exact", "catalog", "초콜릿 / 초코렛", "초콜릿", "영어 chocolate은 ‘초콜릿’으로 적어요.", ["따뜻한 초콜릿 음료를 마셨어요.","초콜릿을 조금씩 나누어 먹었어요."]),
        reference(187, "juice", "loanword", "exact", "catalog", "주스 / 쥬스", "주스", "영어 juice는 ‘주스’라고 적어요.", ["아침에 사과 주스를 마셨어요.","컵에 주스를 따랐어요."]),
        reference(188, "television", "loanword", "exact", "catalog", "텔레비전 / 텔레비젼", "텔레비전", "영어 television은 ‘텔레비전’으로 적어요.", ["텔레비전에서 교육 방송을 보았어요.","텔레비전을 너무 오래 보지 않아요."]),
        reference(189, "message", "loanword", "exact", "catalog", "메시지 / 메세지", "메시지", "영어 message는 ‘메시지’라고 적어요.", ["친구에게 축하 메시지를 보냈어요.","선생님의 메시지를 읽었어요."]),
        reference(190, "accessory", "loanword", "exact", "catalog", "액세서리 / 악세사리", "액세서리", "영어 accessory는 ‘액세서리’로 적어요.", ["가방에 작은 액세서리를 달았어요.","무대 의상에 액세서리를 더했어요."]),
        reference(191, "badminton", "loanword", "exact", "catalog", "배드민턴 / 베드민턴", "배드민턴", "영어 badminton은 ‘배드민턴’으로 적어요.", ["체육 시간에 배드민턴을 쳤어요.","배드민턴 라켓을 준비했어요."]),
        reference(192, "remote-control", "loanword", "exact", "catalog", "리모컨 / 리모콘", "리모컨", "원격 조정 장치를 가리키는 말은 ‘리모컨’이라고 적어요.", ["리모컨으로 텔레비전을 켰어요.","소파 밑에서 리모컨을 찾았어요."]),
        reference(193, "content", "loanword", "exact", "catalog", "콘텐츠 / 컨텐츠", "콘텐츠", "영어 contents를 우리말로 적을 때에는 ‘콘텐츠’라고 적어요.", ["교육 콘텐츠를 활용해 공부했어요.","친구들과 영상 콘텐츠를 만들었어요."]),
        reference(194, "robot", "loanword", "exact", "catalog", "로봇 / 로보트", "로봇", "영어 robot은 ‘로봇’이라고 적어요.", ["로봇이 물건을 옮겼어요.","과학 시간에 로봇을 조립했어요."]),
        reference(195, "placard", "loanword", "exact", "catalog", "플래카드 / 프랑카드", "플래카드", "긴 천이나 종이에 글을 써 내거는 것은 ‘플래카드’예요.", ["응원 문구를 적은 플래카드를 만들었어요.","운동장에 플래카드가 걸렸어요."]),
        reference(196, "cardigan", "loanword", "exact", "catalog", "카디건 / 가디건", "카디건", "앞이 트인 스웨터 모양의 옷은 ‘카디건’이라고 적어요.", ["쌀쌀해서 카디건을 입었어요.","교실 의자에 카디건을 걸어 두었어요."]),
        reference(197, "buffet", "loanword", "exact", "catalog", "뷔페 / 부페", "뷔페", "여러 음식을 차려 놓고 골라 먹는 식당이나 식사 방식은 ‘뷔페’예요.", ["가족과 뷔페에 갔어요.","뷔페에서는 먹을 만큼만 담아요."]),
        reference(198, "navigation", "loanword", "exact", "catalog", "내비게이션 / 네비게이션", "내비게이션", "길 안내 장치를 가리키는 말은 ‘내비게이션’으로 적어요.", ["내비게이션이 빠른 길을 알려 주었어요.","출발 전에 내비게이션을 확인했어요."]),
        reference(199, "stainless", "loanword", "exact", "catalog", "스테인리스 / 스텐레스", "스테인리스", "녹이 잘 슬지 않는 강철을 가리키는 말은 ‘스테인리스’예요.", ["스테인리스 물병을 사용해요.","숟가락은 스테인리스로 만들었어요."]),
        reference(200, "fighting", "loanword", "exact", "catalog", "파이팅 / 화이팅", "파이팅", "힘을 내라고 응원할 때 쓰는 외래어는 ‘파이팅’으로 적어요.", ["우리 팀 파이팅!","친구에게 파이팅이라고 응원했어요."]),
        reference(371, "expansion-baeteori", "loanword", "exact", "expansion", "배터리 / 밧데리", "배터리", "외국에서 들어온 이 말은 한글로 ‘배터리’라고 적어요. ‘밧데리’로 적지 않아요.", ["장난감의 배터리를 갈았어요.","휴대 전화 배터리가 충분해요."]),
        reference(372, "expansion-peuraipaen", "loanword", "exact", "expansion", "프라이팬 / 후라이팬", "프라이팬", "외국에서 들어온 이 말은 한글로 ‘프라이팬’라고 적어요. ‘후라이팬’로 적지 않아요.", ["프라이팬에 달걀을 익혔어요.","뜨거운 프라이팬을 조심하세요."]),
        reference(373, "expansion-rideosip", "loanword", "exact", "expansion", "리더십 / 리더쉽", "리더십", "외국에서 들어온 이 말은 한글로 ‘리더십’라고 적어요. ‘리더쉽’로 적지 않아요.", ["반장이 좋은 리더십을 보여 주었어요.","서로 돕는 리더십을 배웠어요."]),
        reference(374, "expansion-saibeo", "loanword", "exact", "expansion", "사이버 / 싸이버", "사이버", "외국에서 들어온 이 말은 한글로 ‘사이버’라고 적어요. ‘싸이버’로 적지 않아요.", ["사이버 공간에서도 예절을 지켜요.","사이버 안전 교육을 받았어요."]),
        reference(375, "expansion-saiteu", "loanword", "exact", "expansion", "사이트 / 싸이트", "사이트", "외국에서 들어온 이 말은 한글로 ‘사이트’라고 적어요. ‘싸이트’로 적지 않아요.", ["학교 누리집 사이트에 들어갔어요.","안전한 사이트인지 확인했어요."]),
        reference(376, "expansion-sainpen", "loanword", "exact", "expansion", "사인펜 / 싸인펜", "사인펜", "외국에서 들어온 이 말은 한글로 ‘사인펜’라고 적어요. ‘싸인펜’로 적지 않아요.", ["검은 사인펜으로 이름을 썼어요.","여러 색 사인펜으로 꾸몄어요."]),
        reference(377, "expansion-paemilli", "loanword", "exact", "expansion", "패밀리 / 훼밀리", "패밀리", "외국에서 들어온 이 말은 한글로 ‘패밀리’라고 적어요. ‘훼밀리’로 적지 않아요.", ["패밀리 레스토랑에서 식사했어요.","패밀리 행사가 주말에 열려요."]),
        reference(378, "expansion-beurochi", "loanword", "exact", "expansion", "브로치 / 브로찌", "브로치", "외국에서 들어온 이 말은 한글로 ‘브로치’라고 적어요. ‘브로찌’로 적지 않아요.", ["옷깃에 작은 브로치를 달았어요.","나비 모양 브로치가 반짝였어요."]),
        reference(379, "expansion-benchi", "loanword", "exact", "expansion", "벤치 / 벤취", "벤치", "외국에서 들어온 이 말은 한글로 ‘벤치’라고 적어요. ‘벤취’로 적지 않아요.", ["공원 벤치에 앉아 쉬었어요.","나무 아래 벤치가 놓여 있어요."]),
        reference(380, "expansion-rejeo", "loanword", "exact", "expansion", "레저 / 레져", "레저", "외국에서 들어온 이 말은 한글로 ‘레저’라고 적어요. ‘레져’로 적지 않아요.", ["주말에 가족과 레저 활동을 했어요.","안전하게 레저 스포츠를 즐겨요."]),
        reference(381, "expansion-chateu", "loanword", "exact", "expansion", "차트 / 챠트", "차트", "외국에서 들어온 이 말은 한글로 ‘차트’라고 적어요. ‘챠트’로 적지 않아요.", ["조사 결과를 차트로 나타냈어요.","차트를 보고 변화를 설명했어요."]),
        reference(382, "expansion-neteuwokeu", "loanword", "exact", "expansion", "네트워크 / 네트웍", "네트워크", "외국에서 들어온 이 말은 한글로 ‘네트워크’라고 적어요. ‘네트웍’로 적지 않아요.", ["컴퓨터 네트워크를 연결했어요.","학교 네트워크가 잠시 끊겼어요."]),
        reference(383, "expansion-teipeu", "loanword", "exact", "expansion", "테이프 / 테잎", "테이프", "외국에서 들어온 이 말은 한글로 ‘테이프’라고 적어요. ‘테잎’로 적지 않아요.", ["상자에 테이프를 붙였어요.","종이테이프로 작품을 꾸몄어요."]),
        reference(384, "expansion-keoteun", "loanword", "exact", "expansion", "커튼 / 커텐", "커튼", "외국에서 들어온 이 말은 한글로 ‘커튼’라고 적어요. ‘커텐’로 적지 않아요.", ["아침에 창문 커튼을 열었어요.","햇빛이 강해서 커튼을 쳤어요."]),
        reference(385, "expansion-daineomaiteu", "loanword", "exact", "expansion", "다이너마이트 / 다이나마이트", "다이너마이트", "외국에서 들어온 이 말은 한글로 ‘다이너마이트’라고 적어요. ‘다이나마이트’로 적지 않아요.", ["옛 광산에서 다이너마이트를 사용했어요.","다이너마이트는 위험하게 다루면 안 돼요."]),
        reference(386, "expansion-deiteo", "loanword", "exact", "expansion", "데이터 / 데이타", "데이터", "외국에서 들어온 이 말은 한글로 ‘데이터’라고 적어요. ‘데이타’로 적지 않아요.", ["관찰 데이터를 표로 정리했어요.","필요한 데이터를 안전하게 저장했어요."]),
        reference(387, "expansion-dijiteol", "loanword", "exact", "expansion", "디지털 / 디지탈", "디지털", "외국에서 들어온 이 말은 한글로 ‘디지털’라고 적어요. ‘디지탈’로 적지 않아요.", ["디지털 기기를 바르게 사용해요.","사진을 디지털 파일로 저장했어요."]),
        reference(388, "expansion-royeolti", "loanword", "exact", "expansion", "로열티 / 로얄티", "로열티", "외국에서 들어온 이 말은 한글로 ‘로열티’라고 적어요. ‘로얄티’로 적지 않아요.", ["작가는 책 판매에 따라 로열티를 받았어요.","상표 사용 로열티를 계약서에 적었어요."]),
        reference(389, "expansion-roteori", "loanword", "exact", "expansion", "로터리 / 로타리", "로터리", "외국에서 들어온 이 말은 한글로 ‘로터리’라고 적어요. ‘로타리’로 적지 않아요.", ["로터리에서는 차가 도는 방향을 지켜요.","큰 로터리를 지나 학교에 갔어요."]),
        reference(390, "expansion-senteo", "loanword", "exact", "expansion", "센터 / 센타", "센터", "외국에서 들어온 이 말은 한글로 ‘센터’라고 적어요. ‘센타’로 적지 않아요.", ["주민 센터에서 안내를 받았어요.","과학 체험 센터에 다녀왔어요."]),
        reference(391, "expansion-orijineol", "loanword", "exact", "expansion", "오리지널 / 오리지날", "오리지널", "외국에서 들어온 이 말은 한글로 ‘오리지널’라고 적어요. ‘오리지날’로 적지 않아요.", ["이 노래의 오리지널 곡을 들었어요.","오리지널 작품을 전시했어요."]),
        reference(392, "expansion-baelleonseu", "loanword", "exact", "expansion", "밸런스 / 발란스", "밸런스", "외국에서 들어온 이 말은 한글로 ‘밸런스’라고 적어요. ‘발란스’로 적지 않아요.", ["자전거를 탈 때 밸런스를 잡았어요.","공부와 놀이의 밸런스가 필요해요."]),
        reference(393, "expansion-syaesi", "loanword", "exact", "expansion", "섀시 / 샷시", "섀시", "외국에서 들어온 이 말은 한글로 ‘섀시’라고 적어요. ‘샷시’로 적지 않아요.", ["창문의 섀시를 새로 고쳤어요.","튼튼한 섀시가 유리를 받치고 있어요."]),
        reference(394, "expansion-konsepteu", "loanword", "exact", "expansion", "콘셉트 / 컨셉트", "콘셉트", "외국에서 들어온 이 말은 한글로 ‘콘셉트’라고 적어요. ‘컨셉트’로 적지 않아요.", ["축제의 콘셉트를 정했어요.","그림의 콘셉트가 재미있어요."]),
        reference(395, "expansion-tekeunolloji", "loanword", "exact", "expansion", "테크놀로지 / 테크놀러지", "테크놀로지", "외국에서 들어온 이 말은 한글로 ‘테크놀로지’라고 적어요. ‘테크놀러지’로 적지 않아요.", ["새로운 테크놀로지가 생활을 바꾸었어요.","친환경 테크놀로지를 소개했어요."]),
        reference(396, "expansion-baeteon", "loanword", "exact", "expansion", "배턴 / 바톤", "배턴", "외국에서 들어온 이 말은 한글로 ‘배턴’라고 적어요. ‘바톤’로 적지 않아요.", ["이어달리기에서 배턴을 건넸어요.","다음 주자에게 배턴이 전달되었어요."]),
        reference(397, "expansion-direkteori", "loanword", "exact", "expansion", "디렉터리 / 디렉토리", "디렉터리", "외국에서 들어온 이 말은 한글로 ‘디렉터리’라고 적어요. ‘디렉토리’로 적지 않아요.", ["파일을 새 디렉터리에 저장했어요.","사진 디렉터리를 열어 보았어요."]),
        reference(398, "expansion-seupeonji", "loanword", "exact", "expansion", "스펀지 / 스폰지", "스펀지", "외국에서 들어온 이 말은 한글로 ‘스펀지’라고 적어요. ‘스폰지’로 적지 않아요.", ["스펀지에 물을 묻혀 닦았어요.","부드러운 스펀지로 컵을 씻었어요."]),
        reference(399, "expansion-eeokeon", "loanword", "exact", "expansion", "에어컨 / 에어콘", "에어컨", "외국에서 들어온 이 말은 한글로 ‘에어컨’라고 적어요. ‘에어콘’로 적지 않아요.", ["더운 날에는 에어컨을 켰어요.","에어컨 온도를 알맞게 맞추었어요."]),
        reference(400, "expansion-paempeullit", "loanword", "exact", "expansion", "팸플릿 / 팜플렛", "팸플릿", "외국에서 들어온 이 말은 한글로 ‘팸플릿’라고 적어요. ‘팜플렛’로 적지 않아요.", ["박물관 안내 팸플릿을 읽었어요.","행사 팸플릿을 한 장 받았어요."])
    ]
);
