import { defineSpellingEntries, practice, reference } from './schema.js';

export const WORD_SPELLING_ENTRIES = defineSpellingEntries(
    'word',
[
        reference(3, "wen-waen", "general", "context", "base", "웬 / 왠", "대부분 ‘웬’, ‘왠지’만 ‘왠’", "‘어찌 된’이라는 뜻이면 ‘웬’을 써요. ‘왜인지’가 줄어든 ‘왠지’만 따로 기억해요.", ["웬일로 일찍 왔니?","오늘은 왠지 기분이 좋아요."], {"searchable":["웬","왠","웬일","왠일","왠지","웬지"],"detectionPatterns":[{"text":"왠 사람이","target":"왠","right":"웬","lookup":"웬"},{"text":"웬지","target":"웬지","right":"왠지","lookup":"왠지"},{"text":"왠일","target":"왠일","right":"웬일","lookup":"웬일"},{"text":"왠만","target":"왠만","right":"웬만","lookup":"웬만"}],"sourceQuery":"웬"}),
        reference(5, "myeochil", "general", "exact", "base", "며칠 / 몇일", "며칠", "날짜나 날의 수를 물을 때에는 ‘며칠’이라고 적어요.", ["오늘이 몇 월 며칠이지?","며칠 동안 비가 내렸어요."], {"searchable":["며칠","몇일","몇 일"]}),
        reference(6, "geumse", "general", "exact", "base", "금세 / 금새", "금세", "아주 짧은 시간을 나타내는 말은 ‘금세’예요.", ["비가 금세 그쳤어요.","동생은 금세 잠이 들었어요."], {"searchable":["금세","금새","금방"]}),
        reference(7, "oraenman", "general", "exact", "base", "오랜만 / 오랫만", "오랜만", "‘오래간만’이 줄어든 말이므로 ‘오랜만’이라고 적어요.", ["친구를 오랜만에 만났어요.","오랜만에 운동장에 나갔어요."], {"searchable":["오랜만","오랫만","오랜 만"]}),
        reference(8, "yeokhal", "general", "exact", "base", "역할 / 역활", "역할", "자기가 맡아서 하는 일은 ‘역할’이라고 적어요.", ["모둠에서 기록하는 역할을 맡았어요.","배우가 주인공 역할을 맡았어요."]),
        reference(9, "seollem", "general", "exact", "base", "설렘 / 설레임", "설렘", "마음이 두근거리는 느낌은 동사 ‘설레다’에서 온 ‘설렘’이라고 적어요.", ["여행을 앞두고 설렘을 느꼈어요.","새 학기의 설렘이 가득했어요."], {"searchable":["설렘","설레임","설레다"]}),
        reference(17, "kkaekkeusi", "adverb", "exact", "base", "깨끗이 / 깨끗히", "깨끗이", "‘깨끗하다’가 행동을 꾸며 주는 말이 될 때에는 ‘깨끗이’라고 적어요.", ["교실을 깨끗이 청소했어요.","손을 깨끗이 씻었어요."], {"searchable":["깨끗이","깨끗히","깨끗하게"]}),
        reference(18, "gomgomi", "adverb", "exact", "base", "곰곰이 / 곰곰히", "곰곰이", "여러 번 깊이 생각하는 모양은 ‘곰곰이’라고 적어요.", ["문제를 곰곰이 생각했어요.","친구의 말을 곰곰이 되새겼어요."], {"searchable":["곰곰이","곰곰히","곰곰"]}),
        reference(25, "dodaeche", "general", "exact", "catalog", "도대체 / 도데체", "도대체", "어떤 방법으로도 알기 어렵다는 뜻의 말은 ‘도대체’라고 적어요.", ["도대체 무슨 일이 있었니?","이 문제는 도대체 어떻게 푸는 걸까?"]),
        reference(26, "eoieopda", "general", "exact", "catalog", "어이없다 / 어의없다", "어이없다", "너무 뜻밖이어서 기가 막힌다는 뜻은 ‘어이없다’예요.", ["약속을 잊었다니 정말 어이없었어요.","어이없는 실수에 모두가 놀랐어요."]),
        reference(27, "nunsal", "general", "exact", "catalog", "눈살 / 눈쌀", "눈살", "두 눈썹 사이에 잡히는 주름은 ‘눈살’이라고 적어요.", ["시끄러운 소리에 눈살을 찌푸렸어요.","친구가 눈살을 찌푸리지 않게 조심해요."]),
        reference(28, "neokduri", "general", "exact", "catalog", "넋두리 / 넉두리", "넋두리", "불평이나 하소연을 길게 늘어놓는 말은 ‘넋두리’예요.", ["친구에게 속상한 넋두리를 했어요.","넋두리만 하기보다 해결책을 찾아봐요."]),
        reference(29, "seolgeoji", "general", "exact", "catalog", "설거지 / 설겆이", "설거지", "먹고 난 그릇을 씻어 정리하는 일은 ‘설거지’라고 적어요.", ["저녁을 먹고 설거지를 도왔어요.","설거지를 끝내니 부엌이 깨끗해졌어요."]),
        reference(30, "jjigae", "general", "context", "catalog", "찌개 / 찌게", "찌개", "국물이 자작한 음식은 ‘찌개’라고 적어요.", ["된장찌개가 보글보글 끓어요.","따뜻한 찌개를 함께 먹었어요."], {"detectionPatterns":[{"text":"김치찌게","target":"찌게","right":"찌개","lookup":"찌개"},{"text":"된장찌게","target":"찌게","right":"찌개","lookup":"찌개"}]}),
        reference(31, "yukgaejang", "general", "exact", "catalog", "육개장 / 육계장", "육개장", "쇠고기와 여러 나물을 넣어 맵게 끓인 국은 ‘육개장’이에요.", ["점심에 육개장을 먹었어요.","육개장에는 대파가 들어가요."]),
        reference(32, "tteokbokki", "general", "exact", "catalog", "떡볶이 / 떡볶기", "떡볶이", "떡을 양념에 볶아 만든 음식은 ‘떡볶이’라고 적어요.", ["친구와 떡볶이를 나누어 먹었어요.","떡볶이가 매워서 물을 마셨어요."]),
        reference(33, "gopppaegi", "general", "exact", "catalog", "곱빼기 / 곱배기", "곱빼기", "음식을 보통보다 더 많이 주는 것은 ‘곱빼기’예요.", ["아빠는 짜장면 곱빼기를 주문했어요.","양이 많아서 곱빼기는 다 먹기 어려웠어요."]),
        reference(34, "mureupsseuda", "general", "exact", "catalog", "무릅쓰다 / 무릎쓰다", "무릅쓰다", "어려움이나 위험을 참고 견딘다는 뜻은 ‘무릅쓰다’예요.", ["비바람을 무릅쓰고 구조에 나섰어요.","위험을 무릅쓰는 행동은 조심해야 해요."]),
        reference(35, "gapjagi", "general", "exact", "catalog", "갑자기 / 갑짜기", "갑자기", "뜻하지 않은 일이 빠르게 일어날 때 ‘갑자기’라고 적어요.", ["갑자기 비가 내리기 시작했어요.","친구가 갑자기 웃음을 터뜨렸어요."]),
        reference(36, "eochapi", "general", "exact", "catalog", "어차피 / 어짜피", "어차피", "일이 그렇게 될 수밖에 없다는 뜻은 ‘어차피’예요.", ["어차피 해야 할 일이라면 즐겁게 해요.","어차피 만날 거라 함께 가기로 했어요."]),
        reference(37, "hamateomyeon", "general", "exact", "catalog", "하마터면 / 하마트면", "하마터면", "조금만 잘못했으면 큰일이 날 뻔했다는 뜻은 ‘하마터면’이에요.", ["하마터면 계단에서 넘어질 뻔했어요.","하마터면 버스를 놓칠 뻔했어요."]),
        reference(38, "amuteun", "general", "exact", "catalog", "아무튼 / 아뭏든", "아무튼", "앞의 내용을 정리하거나 화제를 돌릴 때 ‘아무튼’이라고 적어요.", ["아무튼 약속은 꼭 지켜야 해요.","아무튼 모두 무사해서 다행이에요."]),
        reference(39, "changpi", "general", "exact", "catalog", "창피 / 챙피", "창피", "부끄럽고 민망한 느낌은 ‘창피’라고 적어요.", ["거짓말한 것이 창피했어요.","실수는 창피한 일이 아니에요."]),
        reference(40, "matchumbeop", "general", "exact", "catalog", "맞춤법 / 마춤법", "맞춤법", "말을 글자로 올바르게 적는 규칙은 ‘맞춤법’이에요.", ["맞춤법을 지켜 글을 썼어요.","모르는 맞춤법을 사전에서 찾았어요."]),
        reference(41, "samgada", "general", "exact", "catalog", "삼가다 / 삼가하다", "삼가다", "말이나 행동을 조심한다는 뜻은 ‘삼가다’ 자체로 써요.", ["복도에서 큰 소리를 삼가 주세요.","위험한 장난은 삼가야 해요."]),
        reference(42, "seoseumji", "general", "exact", "catalog", "서슴지 / 서슴치", "서슴지", "망설이지 않는다는 뜻으로 ‘서슴지 않다’라고 적어요.", ["친구를 위해 도움을 주는 일을 서슴지 않았어요.","옳은 말이라면 서슴지 않고 말했어요."]),
        reference(43, "tongteureo", "general", "exact", "catalog", "통틀어 / 통털어", "통틀어", "있는 것을 모두 합한다는 뜻은 ‘통틀어’예요.", ["우리 반 학생을 통틀어 스무 명이에요.","세 경기를 통틀어 두 골을 넣었어요."]),
        reference(44, "jjagipgi", "general", "exact", "catalog", "짜깁기 / 짜집기", "짜깁기", "여러 조각을 이어 붙이거나 내용을 모아 만드는 것은 ‘짜깁기’예요.", ["천 조각을 짜깁기해 가방을 만들었어요.","다른 글을 짜깁기하지 않고 직접 썼어요."]),
        reference(45, "tteryeoya", "general", "exact", "catalog", "떼려야 / 뗄래야", "떼려야", "‘떼려고 해도’의 뜻으로는 ‘떼려야’라고 적어요.", ["둘은 떼려야 뗄 수 없는 친구예요.","이야기와 그림은 떼려야 뗄 수 없어요."]),
        reference(46, "gaegujaengi", "general", "exact", "catalog", "개구쟁이 / 개구장이", "개구쟁이", "장난이 심하고 짓궂은 아이는 ‘개구쟁이’예요.", ["동생은 장난꾸러기 개구쟁이예요.","개구쟁이 친구가 재미있는 표정을 지었어요."]),
        reference(47, "meotjaengi", "general", "exact", "catalog", "멋쟁이 / 멋장이", "멋쟁이", "멋이 있거나 멋을 잘 부리는 사람은 ‘멋쟁이’예요.", ["할아버지는 모자를 멋지게 쓰는 멋쟁이예요.","친구가 멋쟁이처럼 차려입었어요."]),
        reference(55, "daega", "general", "exact", "catalog", "대가 / 댓가", "대가", "일을 하고 받는 보상이나 큰 업적을 이룬 사람은 ‘대가’라고 적어요.", ["노력의 대가로 상을 받았어요.","그 화가는 풍경화의 대가예요."]),
        reference(65, "hyugesil", "general", "exact", "catalog", "휴게실 / 휴계실", "휴게실", "잠시 쉬는 방은 ‘휴게실’이라고 적어요.", ["휴게실에서 잠깐 쉬었어요.","도서관 휴게실에서는 조용히 말해요."]),
        reference(66, "huihanhada", "general", "exact", "catalog", "희한하다 / 희안하다", "희한하다", "매우 드물거나 신기하다는 뜻은 ‘희한하다’예요.", ["희한한 모양의 구름을 보았어요.","그 마술은 정말 희한했어요."]),
        reference(67, "daegae", "general", "context", "catalog", "대개 / 대게", "대개", "대부분이라는 뜻은 ‘대개’이고, ‘대게’는 게의 한 종류예요.", ["우리 반은 대개 아홉 시에 수업을 시작해요.","겨울에는 해가 대개 일찍 져요."], {"detectionPatterns":[{"text":"대게 일찍","target":"대게","right":"대개","lookup":"대개"},{"text":"대게 아홉","target":"대게","right":"대개","lookup":"대개"}]}),
        reference(68, "yosae", "general", "context", "catalog", "요새 / 요세", "요새", "지금과 가까운 최근을 뜻할 때 ‘요새’라고 적어요.", ["요새 날씨가 많이 더워졌어요.","나는 요새 책 읽기에 빠졌어요."], {"detectionPatterns":[{"text":"요세 날씨","target":"요세","right":"요새","lookup":"요새"},{"text":"나는 요세","target":"요세","right":"요새","lookup":"요새"}]}),
        reference(69, "eotgeuje", "general", "exact", "catalog", "엊그제 / 엇그제", "엊그제", "바로 며칠 전을 뜻하는 말은 ‘엊그제’예요.", ["엊그제 만난 것 같은데 벌써 일주일이 지났어요.","엊그제 심은 씨앗에서 싹이 났어요."]),
        reference(70, "myeotmyeot", "general", "exact", "catalog", "몇몇 / 몆몆", "몇몇", "전체 가운데 많지 않은 일부를 가리킬 때 ‘몇몇’이라고 적어요.", ["몇몇 친구가 발표를 준비했어요.","운동장에 몇몇 사람이 남아 있었어요."]),
        reference(71, "iljjigi", "general", "exact", "catalog", "일찍이 / 일찌기", "일찍이", "이른 때에 또는 전에 이미라는 뜻은 ‘일찍이’예요.", ["아버지는 일찍이 일을 시작하셨어요.","그 선수는 일찍이 재능을 보였어요."]),
        reference(72, "ilili", "adverb", "exact", "catalog", "일일이 / 일일히", "일일이", "하나씩 하나씩 모두라는 뜻은 ‘일일이’라고 적어요.", ["숙제를 일일이 확인했어요.","이름을 일일이 불러 주었어요."]),
        reference(73, "teumteumi", "adverb", "exact", "catalog", "틈틈이 / 틈틈히", "틈틈이", "시간이 날 때마다라는 뜻은 ‘틈틈이’예요.", ["틈틈이 책을 읽었어요.","쉬는 시간마다 틈틈이 연습했어요."]),
        reference(74, "beonbeoni", "adverb", "exact", "catalog", "번번이 / 번번히", "번번이", "매번이라는 뜻은 ‘번번이’라고 적어요.", ["번번이 약속을 잊으면 안 돼요.","우리 팀은 번번이 좋은 경기를 했어요."]),
        reference(75, "satsati", "adverb", "exact", "catalog", "샅샅이 / 샅샅히", "샅샅이", "구석구석 자세히라는 뜻은 ‘샅샅이’예요.", ["방 안을 샅샅이 찾아보았어요.","자료를 샅샅이 살펴보았어요."]),
        reference(76, "natnati", "adverb", "exact", "catalog", "낱낱이 / 낱낱히", "낱낱이", "하나하나 빠짐없이 모두라는 뜻은 ‘낱낱이’예요.", ["그날 일을 낱낱이 설명했어요.","관찰 결과를 낱낱이 기록했어요."]),
        reference(77, "nanari", "adverb", "exact", "catalog", "나날이 / 나날히", "나날이", "날이 갈수록이라는 뜻은 ‘나날이’라고 적어요.", ["실력이 나날이 늘고 있어요.","나무가 나날이 푸르게 자랐어요."]),
        reference(78, "gyeopgyeobi", "adverb", "exact", "catalog", "겹겹이 / 겹겹히", "겹겹이", "여러 겹으로 포개진 모양은 ‘겹겹이’예요.", ["산이 겹겹이 이어져 있어요.","옷을 겹겹이 껴입었어요."]),
        reference(79, "jjamjjami", "adverb", "exact", "catalog", "짬짬이 / 짬짬히", "짬짬이", "시간이 조금씩 날 때마다라는 뜻은 ‘짬짬이’예요.", ["짬짬이 그림을 완성했어요.","여행 중에도 짬짬이 일기를 썼어요."]),
        reference(80, "gipsugi", "adverb", "exact", "catalog", "깊숙이 / 깊숙히", "깊숙이", "안쪽으로 깊이 들어간 모양은 ‘깊숙이’라고 적어요.", ["책을 가방 안에 깊숙이 넣었어요.","동굴 깊숙이 빛이 비쳤어요."]),
        reference(81, "neujimagi", "adverb", "exact", "catalog", "느지막이 / 느즈막히", "느지막이", "시간이 꽤 늦은 듯하게라는 뜻은 ‘느지막이’예요.", ["휴일에는 느지막이 아침을 먹었어요.","해가 느지막이 산 너머로 졌어요."]),
        reference(82, "gakkai", "adverb", "exact", "catalog", "가까이 / 가까히", "가까이", "거리나 관계가 멀지 않다는 뜻의 부사는 ‘가까이’예요.", ["친구가 가까이 다가왔어요.","화면을 너무 가까이 보지 마세요."]),
        reference(83, "soljiki", "adverb", "exact", "catalog", "솔직히 / 솔직이", "솔직히", "거짓이나 숨김 없이 말한다는 뜻의 부사는 ‘솔직히’예요.", ["솔직히 잘못을 말했어요.","내 생각을 솔직히 이야기했어요."]),
        reference(84, "kkomkkomhi", "adverb", "exact", "catalog", "꼼꼼히 / 꼼꼼이", "꼼꼼히", "빈틈이 없도록 자세하게라는 뜻은 ‘꼼꼼히’예요.", ["준비물을 꼼꼼히 챙겼어요.","답을 꼼꼼히 확인했어요."]),
        reference(99, "geondeurida", "general", "exact", "catalog", "건드리다 / 건들이다", "건드리다", "손을 대거나 참견한다는 뜻은 ‘건드리다’예요.", ["전시품을 함부로 건드리지 마세요.","친구의 마음을 건드리는 말을 피했어요."]),
        reference(100, "guburida", "general", "exact", "catalog", "구부리다 / 구푸리다", "구부리다", "한쪽으로 굽게 한다는 뜻은 ‘구부리다’예요.", ["무릎을 천천히 구부렸어요.","종이를 반으로 구부렸어요."]),
        reference(101, "ureoreoboda", "general", "exact", "catalog", "우러러보다 / 우려러보다", "우러러보다", "위를 향해 바라보거나 존경한다는 뜻은 ‘우러러보다’예요.", ["밤하늘을 우러러보았어요.","많은 사람이 그분을 우러러보았어요."]),
        reference(102, "chireuda", "general", "exact", "catalog", "치르다 / 치루다", "치르다", "시험이나 행사, 값을 마친다는 뜻은 ‘치르다’예요.", ["내일 시험을 치러요.","물건값을 치렀어요."]),
        reference(103, "deurikyeoda", "general", "exact", "catalog", "들이켜다 / 들이키다", "들이켜다", "물이나 공기를 한꺼번에 마신다는 뜻은 ‘들이켜다’예요.", ["물을 한 모금 들이켰어요.","밖에 나가 맑은 공기를 들이켰어요."]),
        reference(104, "dwicheojida", "general", "exact", "catalog", "뒤처지다 / 뒤쳐지다", "뒤처지다", "다른 사람보다 늦거나 뒤에 남는다는 뜻은 ‘뒤처지다’예요.", ["연습을 쉬면 친구들보다 뒤처질 수 있어요.","대열에서 뒤처지지 않게 걸었어요."]),
        reference(105, "dwichidakkkeori", "general", "exact", "catalog", "뒤치다꺼리 / 뒤치닥거리", "뒤치다꺼리", "뒤에서 일을 보살펴 주는 수고는 ‘뒤치다꺼리’예요.", ["부모님이 아이들의 뒤치다꺼리를 하셨어요.","행사 뒤치다꺼리를 함께 도왔어요."]),
        reference(106, "neolbeureojida", "general", "exact", "catalog", "널브러지다 / 널부러지다", "널브러지다", "여기저기 흩어져 어지럽게 놓인 모양은 ‘널브러지다’예요.", ["장난감이 방에 널브러져 있었어요.","바닥에 널브러진 책을 정리했어요."]),
        reference(107, "eopjireuda", "general", "exact", "catalog", "엎지르다 / 업지르다", "엎지르다", "그릇을 넘어뜨려 내용물을 쏟는 것은 ‘엎지르다’예요.", ["컵을 건드려 물을 엎질렀어요.","우유를 엎지르지 않게 조심해요."]),
        reference(110, "gudi", "adverb", "exact", "catalog", "굳이 / 구지", "굳이", "일부러 꼭 그렇게 해야 할 필요가 없다는 뜻에는 ‘굳이’를 써요.", ["굳이 지금 말하지 않아도 돼요.","비가 오는데 굳이 밖에 나가지 않았어요."]),
        reference(111, "kkeutnae", "general", "exact", "catalog", "끝내 / 끈내", "끝내", "마침내 또는 마지막까지라는 뜻은 ‘끝내’예요.", ["우리는 끝내 문제를 해결했어요.","그는 끝내 약속을 지켰어요."]),
        reference(112, "jjotgida", "general", "exact", "catalog", "쫓기다 / 쫒기다", "쫓기다", "뒤에서 따라오며 몰리는 것은 ‘쫓기다’라고 적어요.", ["고양이가 강아지에게 쫓겼어요.","시간에 쫓겨 서두르지 않도록 해요."]),
        reference(201, "expansion-gwaenchanhda", "general", "exact", "expansion", "괜찮다 / 괜찬다", "괜찮다", "좋거나 문제될 것이 없다는 뜻이에요. ‘괜찬다’가 아니라 ‘괜찮다’로 적어요.", ["조금 늦어도 괜찮다.","친구가 괜찮다고 웃었어요."]),
        reference(202, "expansion-geokkuro", "general", "exact", "expansion", "거꾸로 / 꺼꾸로", "거꾸로", "순서나 방향이 반대라는 뜻이에요. ‘꺼꾸로’가 아니라 ‘거꾸로’로 적어요.", ["책을 거꾸로 들었어요.","순서를 거꾸로 말하지 마세요."]),
        reference(203, "expansion-gwittim", "general", "exact", "expansion", "귀띔 / 귀뜸", "귀띔", "상대에게 슬며시 일러 주는 일을 말해요. ‘귀뜸’가 아니라 ‘귀띔’로 적어요.", ["친구가 답을 귀띔해 주었어요.","행사 날짜를 미리 귀띔했어요."]),
        reference(204, "expansion-kkaedareum", "general", "exact", "expansion", "깨달음 / 깨닳음", "깨달음", "생각하고 알아낸 것을 나타내는 말이에요. ‘깨닳음’가 아니라 ‘깨달음’로 적어요.", ["실수에서 큰 깨달음을 얻었어요.","책을 읽고 새로운 깨달음이 생겼어요."]),
        reference(205, "expansion-kkeunapul", "general", "exact", "expansion", "끄나풀 / 끈나풀", "끄나풀", "길지 않은 끈의 나머지 조각을 가리켜요. ‘끈나풀’가 아니라 ‘끄나풀’로 적어요.", ["상자에 끄나풀이 매달려 있었어요.","실 끄나풀을 정리했어요."]),
        reference(206, "expansion-dangchoe", "general", "exact", "expansion", "당최 / 당췌", "당최", "도무지 또는 영이라는 뜻으로 쓰는 부사예요. ‘당췌’가 아니라 ‘당최’로 적어요.", ["문제가 당최 풀리지 않았어요.","무슨 말인지 당최 모르겠어요."]),
        reference(208, "expansion-ttakttaguri", "general", "exact", "expansion", "딱따구리 / 딱다구리", "딱따구리", "나무를 쪼아 먹이를 찾는 새 이름이에요. ‘딱다구리’가 아니라 ‘딱따구리’로 적어요.", ["딱따구리가 나무를 쪼아요.","숲에서 딱따구리 소리가 들렸어요."]),
        reference(209, "expansion-mandeum", "general", "exact", "expansion", "만듦 / 만듬", "만듦", "동사 ‘만들다’를 명사처럼 나타낸 꼴이에요. ‘만듬’가 아니라 ‘만듦’로 적어요.", ["함께 만듦의 즐거움을 느꼈어요.","작품을 직접 만듦으로써 자신감이 생겼어요."]),
        reference(210, "expansion-myeoneuri", "general", "exact", "expansion", "며느리 / 며누리", "며느리", "아들의 아내를 가리키는 말이에요. ‘며누리’가 아니라 ‘며느리’로 적어요.", ["할머니는 며느리와 장을 보셨어요.","새 며느리가 가족에게 인사했어요."]),
        reference(211, "expansion-munmae", "general", "exact", "expansion", "뭇매 / 묻매", "뭇매", "여러 사람이 한꺼번에 때리는 매를 뜻해요. ‘묻매’가 아니라 ‘뭇매’로 적어요.", ["잘못된 소문이 사람들의 뭇매를 맞았어요.","거짓말 때문에 비난의 뭇매를 맞았어요."]),
        reference(212, "expansion-baljaguk", "general", "exact", "expansion", "발자국 / 발자욱", "발자국", "발로 밟은 자리에 남은 모양을 말해요. ‘발자욱’가 아니라 ‘발자국’로 적어요.", ["눈 위에 발자국이 남았어요.","모래밭의 발자국을 따라갔어요."]),
        reference(213, "expansion-biroso", "general", "exact", "expansion", "비로소 / 비로서", "비로소", "어느 단계에 이르러서야 드디어라는 뜻이에요. ‘비로서’가 아니라 ‘비로소’로 적어요.", ["연습한 뒤에야 비로소 알게 되었어요.","해가 뜨자 비로소 길이 보였어요."]),
        reference(214, "expansion-saenggakgeondae", "general", "exact", "expansion", "생각건대 / 생각컨대", "생각건대", "생각해 보건대라는 뜻으로 줄여 쓰는 말이에요. ‘생각컨대’가 아니라 ‘생각건대’로 적어요.", ["내가 생각건대 이 방법이 좋아요.","생각건대 지금 출발해야 해요."]),
        reference(215, "expansion-seopseopji", "general", "exact", "expansion", "섭섭지 / 섭섭치", "섭섭지", "‘섭섭하지’가 줄어든 꼴이에요. ‘섭섭치’가 아니라 ‘섭섭지’로 적어요.", ["친구가 와 주어서 섭섭지 않았어요.","결과가 아쉬워도 섭섭지 않게 말했어요."]),
        reference(216, "expansion-sokkumnori", "general", "exact", "expansion", "소꿉놀이 / 소꼽놀이", "소꿉놀이", "아이들이 살림살이를 흉내 내는 놀이예요. ‘소꼽놀이’가 아니라 ‘소꿉놀이’로 적어요.", ["동생과 소꿉놀이를 했어요.","소꿉놀이 그릇을 가지런히 놓았어요."]),
        reference(217, "expansion-seungnak", "general", "exact", "expansion", "승낙 / 승락", "승낙", "남의 부탁이나 요청을 받아들이는 일이에요. ‘승락’가 아니라 ‘승낙’로 적어요.", ["부모님의 승낙을 받았어요.","친구는 부탁을 흔쾌히 승낙했어요."]),
        reference(218, "expansion-ssakduk", "general", "exact", "expansion", "싹둑 / 싹뚝", "싹둑", "가위나 칼로 단번에 자르는 모양을 나타내요. ‘싹뚝’가 아니라 ‘싹둑’로 적어요.", ["색종이를 싹둑 잘랐어요.","긴 끈을 싹둑 끊었어요."]),
        reference(219, "expansion-sseurebatgi", "general", "exact", "expansion", "쓰레받기 / 쓰레받이", "쓰레받기", "비로 쓴 먼지를 받아 내는 도구예요. ‘쓰레받이’가 아니라 ‘쓰레받기’로 적어요.", ["먼지를 쓰레받기에 담았어요.","빗자루와 쓰레받기를 제자리에 두었어요."]),
        reference(220, "expansion-adeungbadeung", "general", "exact", "expansion", "아등바등 / 아둥바둥", "아등바등", "무엇을 이루려고 애를 쓰는 모양이에요. ‘아둥바둥’가 아니라 ‘아등바등’로 적어요.", ["시간에 쫓겨 아등바등 뛰었어요.","혼자 아등바등하지 말고 도움을 청해요."]),
        reference(221, "expansion-ajirangi", "general", "exact", "expansion", "아지랑이 / 아지랭이", "아지랑이", "봄날 멀리에서 아른아른 피어오르는 기운이에요. ‘아지랭이’가 아니라 ‘아지랑이’로 적어요.", ["들판 위로 아지랑이가 피어올랐어요.","따뜻한 길 위에서 아지랑이가 보여요."]),
        reference(222, "expansion-aetdoeda", "general", "exact", "expansion", "앳되다 / 애띠다", "앳되다", "나이에 비해 어려 보인다는 뜻이에요. ‘애띠다’가 아니라 ‘앳되다’로 적어요.", ["앳된 얼굴에 웃음이 번졌어요.","사진 속 모습이 무척 앳되어 보여요."]),
        reference(223, "expansion-ojirap", "general", "exact", "expansion", "오지랖 / 오지랍", "오지랖", "웃옷이나 윗도리의 앞자락을 이르는 말이에요. ‘오지랍’가 아니라 ‘오지랖’로 적어요.", ["남의 일에 오지랖을 넓게 펴지 않아요.","오지랖이 넓다는 말을 들었어요."]),
        reference(224, "expansion-ure", "general", "exact", "expansion", "우레 / 우뢰", "우레", "번개가 칠 때 나는 큰 소리를 뜻해요. ‘우뢰’가 아니라 ‘우레’로 적어요.", ["멀리서 우레가 울렸어요.","우레 같은 박수가 터졌어요."]),
        reference(225, "expansion-umkeum", "general", "exact", "expansion", "움큼 / 웅큼", "움큼", "손으로 한 줌 움켜쥘 만한 분량을 나타내요. ‘웅큼’가 아니라 ‘움큼’로 적어요.", ["모래를 한 움큼 집었어요.","강아지에게 사료를 한 움큼 주었어요."]),
        reference(226, "expansion-euseudaeda", "general", "exact", "expansion", "으스대다 / 으시대다", "으스대다", "잘난 체하며 뽐내는 모습을 뜻해요. ‘으시대다’가 아니라 ‘으스대다’로 적어요.", ["상을 받았다고 으스대지 않았어요.","동생이 새 장난감을 들고 으스댔어요."]),
        reference(227, "expansion-euseuseu", "general", "exact", "expansion", "으스스 / 으시시", "으스스", "차갑거나 무서워서 소름이 끼치는 느낌이에요. ‘으시시’가 아니라 ‘으스스’로 적어요.", ["찬바람에 몸이 으스스 떨렸어요.","어두운 숲길이 조금 으스스했어요."]),
        reference(228, "expansion-jaturi", "general", "exact", "expansion", "자투리 / 짜투리", "자투리", "쓰고 남은 짤막한 부분을 가리켜요. ‘짜투리’가 아니라 ‘자투리’로 적어요.", ["자투리 종이로 책갈피를 만들었어요.","자투리 시간에 책을 읽었어요."]),
        reference(229, "expansion-jukkumi", "general", "exact", "expansion", "주꾸미 / 쭈꾸미", "주꾸미", "여덟 개의 다리가 있는 바다 동물 이름이에요. ‘쭈꾸미’가 아니라 ‘주꾸미’로 적어요.", ["시장 수조에서 주꾸미를 보았어요.","주꾸미는 몸빛을 바꾸기도 해요."]),
        reference(230, "expansion-jitgutta", "general", "exact", "expansion", "짓궂다 / 짓굳다", "짓궂다", "장난스럽게 남을 괴롭히는 데가 있다는 뜻이에요. ‘짓굳다’가 아니라 ‘짓궂다’로 적어요.", ["동생의 짓궂은 장난에 웃었어요.","친구에게 짓궂게 굴지 않아요."]),
        reference(231, "expansion-jjipurida", "general", "exact", "expansion", "찌푸리다 / 찌뿌리다", "찌푸리다", "얼굴이나 눈살을 찡그리는 모습을 나타내요. ‘찌뿌리다’가 아니라 ‘찌푸리다’로 적어요.", ["눈이 부셔서 얼굴을 찌푸렸어요.","냄새를 맡고 코를 찌푸렸어요."]),
        reference(232, "expansion-choseungdal", "general", "exact", "expansion", "초승달 / 초생달", "초승달", "음력 초에 보이는 가느다란 달이에요. ‘초생달’가 아니라 ‘초승달’로 적어요.", ["서쪽 하늘에 초승달이 떴어요.","초승달이 배처럼 휘어 보여요."]),
        reference(233, "expansion-chuseureuda", "general", "exact", "expansion", "추스르다 / 추스리다", "추스르다", "흩어진 것을 정리하거나 마음을 가다듬는다는 뜻이에요. ‘추스리다’가 아니라 ‘추스르다’로 적어요.", ["마음을 추스르고 다시 시작했어요.","짐을 추슬러 가방에 넣었어요."]),
        reference(234, "expansion-pyonmal", "general", "exact", "expansion", "푯말 / 표말", "푯말", "어떤 것을 표시하기 위해 세운 말뚝이나 판이에요. ‘표말’가 아니라 ‘푯말’로 적어요.", ["갈림길의 푯말을 확인했어요.","화단에 꽃 이름 푯말을 세웠어요."]),
        reference(236, "expansion-huyujeung", "general", "exact", "expansion", "후유증 / 후유쯩", "후유증", "병이나 사고 뒤에 남는 증상을 뜻해요. ‘후유쯩’가 아니라 ‘후유증’로 적어요.", ["감기 후유증으로 기침이 남았어요.","사고의 후유증을 치료받았어요."]),
        reference(237, "expansion-heunkoehi", "general", "exact", "expansion", "흔쾌히 / 흔쾌이", "흔쾌히", "기쁘고 시원스럽게 받아들이는 모양이에요. ‘흔쾌이’가 아니라 ‘흔쾌히’로 적어요.", ["친구가 부탁을 흔쾌히 들어주었어요.","선생님은 질문을 흔쾌히 받아 주셨어요."]),
        reference(238, "expansion-gyeolttannada", "general", "exact", "expansion", "결딴나다 / 결단나다", "결딴나다", "어떤 일이 아주 망가져 끝장나는 것을 뜻해요. ‘결단나다’가 아니라 ‘결딴나다’로 적어요.", ["장난감이 완전히 결딴났어요.","무리하게 쓰면 기계가 결딴날 수 있어요."]),
        reference(239, "expansion-gurenarut", "general", "exact", "expansion", "구레나룻 / 구렛나루", "구레나룻", "귀밑에서 턱 쪽으로 난 수염을 말해요. ‘구렛나루’가 아니라 ‘구레나룻’로 적어요.", ["그 배우는 구레나룻을 길렀어요.","구레나룻을 짧게 다듬었어요."]),
        reference(240, "expansion-nungop", "general", "exact", "expansion", "눈곱 / 눈꼽", "눈곱", "눈에서 나온 진득한 것이 말라붙은 것을 말해요. ‘눈꼽’가 아니라 ‘눈곱’로 적어요.", ["세수하며 눈곱을 닦았어요.","아침에 눈곱이 끼었어요."]),
        reference(241, "expansion-dakkdalhada", "general", "exact", "expansion", "닦달하다 / 닥달하다", "닦달하다", "남을 몰아붙여 다그치는 것을 뜻해요. ‘닥달하다’가 아니라 ‘닦달하다’로 적어요.", ["동생을 자꾸 닦달하지 마세요.","빨리하라고 닦달하면 마음이 급해져요."]),
        reference(242, "expansion-dolmengi", "general", "exact", "expansion", "돌멩이 / 돌맹이", "돌멩이", "크지 않은 돌을 가리키는 말이에요. ‘돌맹이’가 아니라 ‘돌멩이’로 적어요.", ["길가의 돌멩이를 주웠어요.","연못에 돌멩이를 던지지 않아요."]),
        reference(243, "expansion-deuridakchida", "general", "exact", "expansion", "들이닥치다 / 들이닦치다", "들이닥치다", "갑자기 안으로 들어오거나 닥쳐오는 것을 말해요. ‘들이닦치다’가 아니라 ‘들이닥치다’로 적어요.", ["소나기가 갑자기 들이닥쳤어요.","아이들이 교실로 한꺼번에 들이닥쳤어요."]),
        reference(244, "expansion-meotjjeokda", "general", "exact", "expansion", "멋쩍다 / 멋적다", "멋쩍다", "어색하고 쑥스럽다는 뜻이에요. ‘멋적다’가 아니라 ‘멋쩍다’로 적어요.", ["칭찬을 받으니 조금 멋쩍었어요.","실수한 아이가 멋쩍게 웃었어요."]),
        reference(245, "expansion-mopsi", "general", "exact", "expansion", "몹시 / 몹씨", "몹시", "더할 수 없이 매우라는 뜻이에요. ‘몹씨’가 아니라 ‘몹시’로 적어요.", ["바람이 몹시 세게 불었어요.","친구를 만나서 몹시 반가웠어요."]),
        reference(246, "expansion-midaji", "general", "exact", "expansion", "미닫이 / 미다지", "미닫이", "옆으로 밀어서 여닫는 문을 말해요. ‘미다지’가 아니라 ‘미닫이’로 적어요.", ["미닫이를 살며시 열었어요.","교실 뒤쪽에 미닫이문이 있어요."]),
        reference(247, "expansion-mitdong", "general", "exact", "expansion", "밑동 / 밑둥", "밑동", "나무나 기둥의 맨 아래 부분이에요. ‘밑둥’가 아니라 ‘밑동’로 적어요.", ["나무 밑동에 버섯이 났어요.","기둥 밑동을 단단히 고정했어요."]),
        reference(248, "expansion-banjitgori", "general", "exact", "expansion", "반짇고리 / 반짓고리", "반짇고리", "바늘과 실 같은 바느질 도구를 담는 그릇이에요. ‘반짓고리’가 아니라 ‘반짇고리’로 적어요.", ["반짇고리에서 실을 꺼냈어요.","할머니의 반짇고리에는 단추가 많아요."]),
        reference(249, "expansion-horuragi", "general", "exact", "expansion", "호루라기 / 호르라기", "호루라기", "입으로 불어 신호를 내는 작은 도구를 말해요. ‘호르라기’가 아니라 ‘호루라기’로 적어요.", ["선생님이 호루라기를 불었어요.","경기 시작을 호루라기로 알렸어요."]),
        reference(250, "expansion-seomtteuk", "general", "exact", "expansion", "섬뜩 / 섬뜻", "섬뜩", "갑자기 소름이 끼치도록 무서운 느낌이에요. ‘섬뜻’가 아니라 ‘섬뜩’로 적어요.", ["큰 소리에 가슴이 섬뜩했어요.","무서운 이야기를 듣고 섬뜩 놀랐어요."]),
        reference(251, "expansion-sidapjanhda", "general", "exact", "expansion", "시답잖다 / 시덥잖다", "시답잖다", "대수롭지 않거나 마음에 들지 않는다는 뜻이에요. ‘시덥잖다’가 아니라 ‘시답잖다’로 적어요.", ["시답잖은 장난은 그만해요.","그 이야기는 시답잖게 들렸어요."]),
        reference(252, "expansion-sillangi", "general", "exact", "expansion", "실랑이 / 실갱이", "실랑이", "서로 자기주장을 고집하며 옥신각신하는 일이에요. ‘실갱이’가 아니라 ‘실랑이’로 적어요.", ["차례를 두고 작은 실랑이가 벌어졌어요.","두 사람의 실랑이가 곧 끝났어요."]),
        reference(253, "expansion-saengttungmatda", "general", "exact", "expansion", "생뚱맞다 / 쌩뚱맞다", "생뚱맞다", "말이나 행동이 상황과 어울리지 않는다는 뜻이에요. ‘쌩뚱맞다’가 아니라 ‘생뚱맞다’로 적어요.", ["갑자기 생뚱맞은 질문을 했어요.","그 대답은 조금 생뚱맞았어요."]),
        reference(254, "expansion-eonggeopgyeol", "general", "exact", "expansion", "엉겁결 / 엉겹결", "엉겁결", "미처 생각하지 못한 사이를 뜻해요. ‘엉겹결’가 아니라 ‘엉겁결’로 적어요.", ["엉겁결에 손을 번쩍 들었어요.","공이 날아와 엉겁결에 피했어요."]),
        reference(255, "expansion-udukeoni", "general", "exact", "expansion", "우두커니 / 우두머니", "우두커니", "멍하니 가만히 서 있거나 앉아 있는 모양이에요. ‘우두머니’가 아니라 ‘우두커니’로 적어요.", ["창밖을 우두커니 바라보았어요.","강아지가 문 앞에 우두커니 앉았어요."]),
        reference(256, "expansion-jageumachi", "general", "exact", "expansion", "자그마치 / 자그만치", "자그마치", "예상보다 훨씬 많거나 크게 느껴짐을 나타내요. ‘자그만치’가 아니라 ‘자그마치’로 적어요.", ["참가자가 자그마치 백 명이나 되었어요.","책을 자그마치 열 권이나 읽었어요."]),
        reference(257, "expansion-jaetteori", "general", "exact", "expansion", "재떨이 / 재털이", "재떨이", "담뱃재를 떨어 놓는 그릇을 말해요. ‘재털이’가 아니라 ‘재떨이’로 적어요.", ["탁자 위 재떨이를 치웠어요.","재떨이는 아이 손이 닿지 않는 곳에 두었어요."]),
        reference(258, "expansion-jeolchejeolmyeong", "general", "exact", "expansion", "절체절명 / 절대절명", "절체절명", "몸이 끊어지고 목숨이 끊어질 만큼 위급한 때를 뜻해요. ‘절대절명’가 아니라 ‘절체절명’로 적어요.", ["주인공이 절체절명의 위기를 넘겼어요.","절체절명의 순간에도 침착했어요."]),
        reference(259, "expansion-jokjipge", "general", "exact", "expansion", "족집게 / 쪽집게", "족집게", "잔털이나 가시를 집어 뽑는 작은 도구예요. ‘쪽집게’가 아니라 ‘족집게’로 적어요.", ["족집게로 작은 가시를 뽑았어요.","서랍에서 족집게를 찾았어요."]),
        reference(260, "expansion-pokbal", "general", "exact", "expansion", "폭발 / 폭팔", "폭발", "불이 붙어 갑자기 터지는 일을 말해요. ‘폭팔’가 아니라 ‘폭발’로 적어요.", ["풍선이 큰 소리를 내며 폭발했어요.","과학실에서는 폭발 사고를 조심해요."]),
        reference(261, "expansion-haelssukhada", "general", "exact", "expansion", "핼쑥하다 / 핼쓱하다", "핼쑥하다", "얼굴에 핏기가 없고 마른 듯하다는 뜻이에요. ‘핼쓱하다’가 아니라 ‘핼쑥하다’로 적어요.", ["감기를 앓아 얼굴이 핼쑥해졌어요.","밤을 새운 형의 얼굴이 핼쑥했어요."]),
        reference(262, "expansion-naburaengi", "general", "exact", "expansion", "나부랭이 / 나부랑이", "나부랭이", "물건의 자질구레한 한 조각을 낮잡아 이르는 말이에요. ‘나부랑이’가 아니라 ‘나부랭이’로 적어요.", ["종이 나부랭이를 한데 모았어요.","천 나부랭이도 버리지 않고 모았어요."]),
        reference(263, "expansion-nangtteoreoji", "general", "exact", "expansion", "낭떠러지 / 낭떨어지", "낭떠러지", "깎아지른 듯한 언덕의 끝을 말해요. ‘낭떨어지’가 아니라 ‘낭떠러지’로 적어요.", ["낭떠러지 가까이 가지 마세요.","산길 옆에 가파른 낭떠러지가 있었어요."]),
        reference(264, "expansion-neoljikhada", "general", "exact", "expansion", "널찍하다 / 널직하다", "널찍하다", "꽤 넓다는 뜻이에요. ‘널직하다’가 아니라 ‘널찍하다’로 적어요.", ["교실이 생각보다 널찍했어요.","널찍한 운동장에서 뛰어놀았어요."]),
        reference(265, "expansion-neulgeumak", "general", "exact", "expansion", "늘그막 / 늙으막", "늘그막", "늙어 가는 무렵을 뜻해요. ‘늙으막’가 아니라 ‘늘그막’로 적어요.", ["할아버지는 늘그막에 그림을 배우셨어요.","늘그막까지 건강하게 지내셨어요."]),
        reference(266, "expansion-daemullim", "general", "exact", "expansion", "대물림 / 되물림", "대물림", "재산이나 특징을 다음 세대에 물려주는 일을 말해요. ‘되물림’가 아니라 ‘대물림’로 적어요.", ["가족의 솜씨가 대물림되었어요.","좋은 습관을 대물림하고 싶어요."]),
        reference(267, "expansion-deoburukhada", "general", "exact", "expansion", "더부룩하다 / 더부럭하다", "더부룩하다", "배 속이 그득하고 편하지 않다는 뜻이에요. ‘더부럭하다’가 아니라 ‘더부룩하다’로 적어요.", ["급하게 먹어서 속이 더부룩해요.","배가 더부룩할 때는 잠시 쉬어요."]),
        reference(268, "expansion-deomteogi", "general", "exact", "expansion", "덤터기 / 덤테기", "덤터기", "남에게 억지로 뒤집어씌우는 허물이나 큰 부담을 뜻해요. ‘덤테기’가 아니라 ‘덤터기’로 적어요.", ["친구에게 잘못의 덤터기를 씌우지 마세요.","엉뚱한 사람이 덤터기를 썼어요."]),
        reference(269, "expansion-donggodongnak", "general", "exact", "expansion", "동고동락 / 동거동락", "동고동락", "괴로움과 즐거움을 함께한다는 뜻이에요. ‘동거동락’가 아니라 ‘동고동락’로 적어요.", ["친구들과 동고동락하며 연습했어요.","한 팀으로 동고동락한 사이예요."]),
        practice(411, "practice-spelling-quiz-011", "general", "context", "(왠 / 웬) 사람이 우리 집에 찾아왔다.", "웬", "‘어찌 된’이라는 뜻일 때에는 ‘웬’을 써요."),
        practice(412, "practice-spelling-quiz-012", "general", "context", "오늘은 (왠지 / 웬지) 기분이 좋다.", "왠지", "‘왜인지’가 줄어든 말은 ‘왠지’예요."),
        practice(413, "practice-spelling-quiz-013", "general", "context", "이게 (왠일 / 웬일)이야?", "웬일", "‘웬일’이 바른 표현이에요."),
        practice(414, "practice-spelling-quiz-014", "general", "context", "(왠만하면 / 웬만하면) 친구와 사이좋게 지내자.", "웬만하면", "‘웬만하다’가 바른 말이에요."),
        practice(415, "practice-spelling-quiz-015", "general", "context", "방학까지 (몇일 / 며칠) 남았니?", "며칠", "‘몇일’이 아니라 ‘며칠’이라고 써요."),
        practice(416, "practice-spelling-quiz-016", "general", "context", "너 생일이 몇 월 (몇 일 / 며칠)이야?", "며칠", "날짜를 물을 때에도 ‘며칠’을 써요."),
        practice(417, "practice-spelling-quiz-017", "general", "context", "친구를 (오랫만에 / 오랜만에) 만났다.", "오랜만에", "‘오랫만’이 아니라 ‘오랜만’이라고 써요."),
        practice(418, "practice-spelling-quiz-018", "general", "context", "우리는 (오랜동안 / 오랫동안) 이야기를 나눴다.", "오랫동안", "긴 시간 동안이라는 뜻은 ‘오랫동안’이에요."),
        practice(419, "practice-spelling-quiz-019", "adverb", "context", "아이스크림이 (금새 / 금세) 녹았다.", "금세", "아주 짧은 시간 안에라는 뜻은 ‘금세’예요."),
        practice(420, "practice-spelling-quiz-020", "adverb", "context", "벌써 숙제를 끝냈다니 정말 (금새 / 금세) 했구나.", "금세", "‘금시에’가 줄어든 말은 ‘금세’예요."),
        practice(421, "practice-spelling-quiz-021", "general", "context", "저녁을 먹고 (설겆이 / 설거지)를 했다.", "설거지", "‘설거지’가 표준어예요."),
        practice(422, "practice-spelling-quiz-022", "adverb", "context", "교실을 (깨끗히 / 깨끗이) 청소했다.", "깨끗이", "‘깨끗이’가 바른 표현이에요."),
        practice(423, "practice-spelling-quiz-023", "adverb", "context", "시험지를 (꼼꼼이 / 꼼꼼히) 살펴보았다.", "꼼꼼히", "‘꼼꼼히’가 바른 표현이에요."),
        practice(424, "practice-spelling-quiz-024", "adverb", "context", "의자에 (가만이 / 가만히) 앉아 있었다.", "가만히", "‘가만히’가 바른 표현이에요."),
        practice(425, "practice-spelling-quiz-025", "adverb", "context", "문제를 (곰곰히 / 곰곰이) 생각했다.", "곰곰이", "‘곰곰이’가 바른 표현이에요."),
        practice(426, "practice-spelling-quiz-026", "adverb", "context", "시간이 날 때마다 (틈틈히 / 틈틈이) 책을 읽었다.", "틈틈이", "‘틈틈이’가 바른 표현이에요."),
        practice(427, "practice-spelling-quiz-027", "adverb", "context", "선생님께서 숙제를 (일일히 / 일일이) 확인하셨다.", "일일이", "‘일일이’가 바른 표현이에요."),
        practice(428, "practice-spelling-quiz-028", "adverb", "context", "내 생각을 (솔직이 / 솔직히) 말했다.", "솔직히", "‘솔직히’가 바른 표현이에요."),
        practice(429, "practice-spelling-quiz-029", "adverb", "context", "친구의 말을 (자세이 / 자세히) 들어 보았다.", "자세히", "‘자세히’가 바른 표현이에요."),
        practice(430, "practice-spelling-quiz-030", "adverb", "context", "발표를 (천천이 / 천천히) 시작했다.", "천천히", "‘천천히’가 바른 표현이에요."),
        practice(460, "practice-spelling-quiz-060", "general", "context", "내 (바램 / 바람)은 가족이 행복한 것이다.", "바람", "소망을 뜻할 때에는 ‘바람’이라고 써요."),
        practice(463, "practice-spelling-quiz-063", "general", "context", "너무 황당해서 (어의가 / 어이가) 없었다.", "어이가", "‘어이없다’가 바른 표현이에요."),
        practice(464, "practice-spelling-quiz-064", "general", "context", "정말 (희안한 / 희한한) 일이 생겼다.", "희한한", "‘희한하다’가 바른 표현이에요."),
        practice(465, "practice-spelling-quiz-065", "general", "context", "모둠에서 각자의 (역활 / 역할)을 정했다.", "역할", "‘역활’이 아니라 ‘역할’이라고 써요."),
        practice(466, "practice-spelling-quiz-066", "general", "context", "수박을 (통채로 / 통째로) 가져왔다.", "통째로", "나누지 않은 덩어리 전부를 뜻할 때에는 ‘통째로’를 써요.")
    ]
);
