-- 서비스 현황(접속·AI 호출·트래픽)과 장애 알림 (2026-08-21)
--
-- 배경: 지금은 "얼마나 쓰이는지" 를 알려면 표를 직접 조회해야 하고, **장애가 나도 선생님이
--       알려 주셔야 안다**. 8/18 에는 디스크가 차서 앱이 내려갔는데 그것도 뒤늦게 알았다.
--
-- 이 마이그레이션이 만드는 것:
--   1) system_daily_metrics — 하루 한 줄. 트래픽·디스크처럼 **지금 값을 재야만 아는 것**을 적는다.
--      접속·AI 호출·글 수는 이미 다른 표에 쌓이므로 여기 적지 않고 그때그때 센다(두 벌로 두면 어긋난다).
--   2) system_alert_events — 알림 이력. **같은 문제로 반복해서 보내지 않게** 상태를 여기서 쥔다.
--      앱이 30분 죽어 있으면 6통이 오고, 그러면 곧 메일을 안 읽게 되어 알림이 있으나 마나가 된다.

BEGIN;

CREATE TABLE IF NOT EXISTS public.system_daily_metrics (
    metric_day        DATE PRIMARY KEY,
    -- 트래픽은 컨테이너가 주고받은 누적 바이트의 하루치 증가분이다. 정확한 회선 사용량은 아니고
    -- **경향을 보는 용도**다(정확히 재려면 접근 로그를 켜야 하는데 디스크를 먹는다).
    rx_bytes          BIGINT,
    tx_bytes          BIGINT,
    disk_free_gb      NUMERIC(10, 1),
    db_size_mb        NUMERIC(12, 1),
    container_total   INTEGER,
    container_healthy INTEGER,
    recorded_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

/*
 * 알림은 "상태" 다. 같은 문제가 이어지는 동안은 한 줄이고, 풀리면 그 줄이 닫힌다.
 * alert_key 예: app_down · disk_low · backup_failed · container_down
 */
CREATE TABLE IF NOT EXISTS public.system_alert_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_key    TEXT NOT NULL,
    status       TEXT NOT NULL DEFAULT 'open',
    detail       TEXT,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at   TIMESTAMPTZ,
    notified_at   TIMESTAMPTZ,
    CONSTRAINT system_alert_events_status_check CHECK (status IN ('open', 'resolved'))
);

-- 열려 있는 알림은 종류마다 하나뿐이다. 이 제약이 중복 발송을 막는 마지막 방어선이다.
CREATE UNIQUE INDEX IF NOT EXISTS system_alert_events_open_key_idx
    ON public.system_alert_events (alert_key) WHERE status = 'open';
CREATE INDEX IF NOT EXISTS system_alert_events_recent_idx
    ON public.system_alert_events (last_seen_at DESC);

-- 두 표 모두 관리자만 RPC 로 읽는다. 직접 접근은 닫는다.
ALTER TABLE public.system_daily_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_alert_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.system_daily_metrics FROM anon, authenticated;
REVOKE ALL ON TABLE public.system_alert_events FROM anon, authenticated;

COMMIT;

BEGIN;

/*
 * 관리자 `서비스 현황` 화면이 읽는 한 번의 조회.
 *
 * 화면이 여러 번 조회하지 않도록 요약·추세·알림을 한 덩어리로 준다.
 * 접속·AI 호출·글 수는 원본 표에서 그때그때 센다 — 하루 한 줄에 베껴 두면 두 값이 어긋난다.
 */
CREATE OR REPLACE FUNCTION public.admin_get_service_overview_v1(p_trend_days INTEGER DEFAULT 30)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_days INTEGER := LEAST(GREATEST(COALESCE(p_trend_days, 30), 7), 90);
    v_today JSONB;
    v_week JSONB;
    v_ai_scopes JSONB;
    v_trend JSONB;
    v_latest JSONB;
    v_alerts JSONB;
BEGIN
    IF public.auth_user_role() <> 'ADMIN' THEN
        RAISE EXCEPTION '관리자만 볼 수 있습니다.' USING ERRCODE = '42501';
    END IF;

    SELECT jsonb_build_object(
        'teachers', (SELECT count(*) FROM public.profiles
                     WHERE role = 'TEACHER' AND last_login_at >= date_trunc('day', NOW())),
        'students', (SELECT count(*) FROM public.students
                     WHERE last_login >= date_trunc('day', NOW())),
        'ai_calls', (SELECT count(*) FROM public.ai_request_events
                     WHERE created_at >= date_trunc('day', NOW())),
        'posts',    (SELECT count(*) FROM public.student_posts
                     WHERE created_at >= date_trunc('day', NOW()))
    ) INTO v_today;

    SELECT jsonb_build_object(
        'teachers', (SELECT count(*) FROM public.profiles
                     WHERE role = 'TEACHER' AND last_login_at >= NOW() - INTERVAL '7 days'),
        'students', (SELECT count(*) FROM public.students
                     WHERE last_login >= NOW() - INTERVAL '7 days'),
        'ai_calls', (SELECT count(*) FROM public.ai_request_events
                     WHERE created_at >= NOW() - INTERVAL '7 days'),
        'posts',    (SELECT count(*) FROM public.student_posts
                     WHERE created_at >= NOW() - INTERVAL '7 days')
    ) INTO v_week;

    -- AI 호출은 종류별로 나눠 본다. 어디서 비용이 나는지가 여기서 갈린다.
    SELECT COALESCE(jsonb_object_agg(scope, cnt), '{}'::jsonb) INTO v_ai_scopes
    FROM (
        SELECT scope, count(*) AS cnt FROM public.ai_request_events
        WHERE created_at >= NOW() - (v_days || ' days')::INTERVAL
        GROUP BY scope
    ) s;

    -- 추세: 하루 한 줄. 기록이 없는 날은 빠진다(스크립트가 아직 안 돌았거나 꺼진 날).
    SELECT COALESCE(jsonb_agg(to_jsonb(d) ORDER BY d.metric_day), '[]'::jsonb) INTO v_trend
    FROM (
        SELECT metric_day, rx_bytes, tx_bytes, disk_free_gb, db_size_mb,
               container_total, container_healthy
        FROM public.system_daily_metrics
        WHERE metric_day >= (CURRENT_DATE - v_days)
        ORDER BY metric_day
    ) d;

    SELECT to_jsonb(m) INTO v_latest FROM (
        SELECT metric_day, rx_bytes, tx_bytes, disk_free_gb, db_size_mb,
               container_total, container_healthy, recorded_at
        FROM public.system_daily_metrics ORDER BY metric_day DESC LIMIT 1
    ) m;

    SELECT COALESCE(jsonb_agg(to_jsonb(a) ORDER BY a.last_seen_at DESC), '[]'::jsonb) INTO v_alerts
    FROM (
        SELECT alert_key, status, detail, first_seen_at, last_seen_at, resolved_at, notified_at
        FROM public.system_alert_events
        ORDER BY last_seen_at DESC LIMIT 20
    ) a;

    RETURN jsonb_build_object(
        'version', 1,
        'trend_days', v_days,
        'today', v_today,
        'week', v_week,
        'ai_scopes', v_ai_scopes,
        'trend', v_trend,
        'latest', COALESCE(v_latest, 'null'::jsonb),
        'alerts', v_alerts,
        'open_alerts', (SELECT count(*) FROM public.system_alert_events WHERE status = 'open')
    );
END;
$$;

REVOKE ALL ON FUNCTION public.admin_get_service_overview_v1(INTEGER) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_get_service_overview_v1(INTEGER) TO authenticated, service_role;

COMMIT;

BEGIN;

-- 하루 한 줄 기록. 같은 날 여러 번 불러도 마지막 값으로 덮는다.
CREATE OR REPLACE FUNCTION public.record_system_daily_metric_v1(
    p_day DATE,
    p_rx_bytes BIGINT,
    p_tx_bytes BIGINT,
    p_disk_free_gb NUMERIC,
    p_db_size_mb NUMERIC,
    p_container_total INTEGER,
    p_container_healthy INTEGER
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    -- 호스트 스크립트만 부른다. 화면에서는 부를 일이 없다.
    -- 호스트 스크립트는 supabase_admin 으로 직접 붙어 auth_user_role() 이 빈 문자열이다.
    -- 로그인한 교사·학생만 막는다(그쪽에는 EXECUTE 권한도 주지 않았다).
    IF public.auth_user_role() NOT IN ('', 'ADMIN') THEN
        RAISE EXCEPTION '기록 권한이 없습니다.' USING ERRCODE = '42501';
    END IF;
    IF p_day IS NULL OR p_day > CURRENT_DATE + 1 THEN
        RAISE EXCEPTION '기록할 날짜가 올바르지 않습니다.' USING ERRCODE = '22023';
    END IF;

    INSERT INTO public.system_daily_metrics AS m (
        metric_day, rx_bytes, tx_bytes, disk_free_gb, db_size_mb,
        container_total, container_healthy, recorded_at
    ) VALUES (
        p_day, p_rx_bytes, p_tx_bytes, p_disk_free_gb, p_db_size_mb,
        p_container_total, p_container_healthy, NOW()
    )
    ON CONFLICT (metric_day) DO UPDATE SET
        rx_bytes = EXCLUDED.rx_bytes,
        tx_bytes = EXCLUDED.tx_bytes,
        disk_free_gb = EXCLUDED.disk_free_gb,
        db_size_mb = EXCLUDED.db_size_mb,
        container_total = EXCLUDED.container_total,
        container_healthy = EXCLUDED.container_healthy,
        recorded_at = NOW();

    -- 오래된 기록은 버린다. 하루 한 줄이라 2년이면 730줄이고, 그 이상은 볼 일이 없다.
    DELETE FROM public.system_daily_metrics WHERE metric_day < CURRENT_DATE - 730;

    RETURN jsonb_build_object('success', TRUE, 'day', p_day);
END;
$$;

/*
 * 장애 상태를 적고 **메일을 보내야 하는지 알려 준다**.
 *
 * ⚠️ 여기가 이 기능의 핵심이다. 스크립트가 5분마다 부르므로, 상태가 그대로면 `should_notify`
 * 는 false 다. 앱이 30분 죽어 있어도 메일은 처음 1통과 복구 1통뿐이다.
 * 이 판단을 스크립트에 두면 스크립트가 재시작될 때마다 다시 보내게 된다.
 */
CREATE OR REPLACE FUNCTION public.record_system_alert_v1(
    p_alert_key TEXT,
    p_is_problem BOOLEAN,
    p_detail TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_key TEXT := btrim(COALESCE(p_alert_key, ''));
    v_detail TEXT := left(btrim(COALESCE(p_detail, '')), 500);
    v_open_id BIGINT;
    v_should_notify BOOLEAN := FALSE;
    v_event TEXT := 'unchanged';
BEGIN
    -- 호스트 스크립트는 supabase_admin 으로 직접 붙어 auth_user_role() 이 빈 문자열이다.
    -- 로그인한 교사·학생만 막는다(그쪽에는 EXECUTE 권한도 주지 않았다).
    IF public.auth_user_role() NOT IN ('', 'ADMIN') THEN
        RAISE EXCEPTION '기록 권한이 없습니다.' USING ERRCODE = '42501';
    END IF;
    IF v_key !~ '^[a-z][a-z0-9_]{1,40}$' THEN
        RAISE EXCEPTION '알림 종류 이름이 올바르지 않습니다.' USING ERRCODE = '22023';
    END IF;

    SELECT id INTO v_open_id FROM public.system_alert_events
    WHERE alert_key = v_key AND status = 'open';

    IF p_is_problem THEN
        IF v_open_id IS NULL THEN
            -- 새로 생긴 문제 → 한 번만 알린다.
            INSERT INTO public.system_alert_events(alert_key, status, detail, notified_at)
            VALUES (v_key, 'open', NULLIF(v_detail, ''), NOW());
            v_should_notify := TRUE;
            v_event := 'opened';
        ELSE
            -- 이어지는 문제 → 마지막 확인 시각만 갱신하고 조용히 둔다.
            UPDATE public.system_alert_events
            SET last_seen_at = NOW(), detail = COALESCE(NULLIF(v_detail, ''), detail)
            WHERE id = v_open_id;
        END IF;
    ELSE
        IF v_open_id IS NOT NULL THEN
            -- 풀렸다 → 복구도 한 번 알린다. 알림만 오고 끝나면 고쳐졌는지 모른다.
            UPDATE public.system_alert_events
            SET status = 'resolved', resolved_at = NOW(), last_seen_at = NOW(), notified_at = NOW()
            WHERE id = v_open_id;
            v_should_notify := TRUE;
            v_event := 'resolved';
        END IF;
    END IF;

    -- 오래된 이력은 버린다.
    DELETE FROM public.system_alert_events
    WHERE status = 'resolved' AND resolved_at < NOW() - INTERVAL '180 days';

    RETURN jsonb_build_object('should_notify', v_should_notify, 'event', v_event, 'alert_key', v_key);
END;
$$;

REVOKE ALL ON FUNCTION public.record_system_daily_metric_v1(DATE, BIGINT, BIGINT, NUMERIC, NUMERIC, INTEGER, INTEGER) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.record_system_alert_v1(TEXT, BOOLEAN, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_system_daily_metric_v1(DATE, BIGINT, BIGINT, NUMERIC, NUMERIC, INTEGER, INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION public.record_system_alert_v1(TEXT, BOOLEAN, TEXT) TO service_role;

NOTIFY pgrst, 'reload schema';

COMMIT;
