-- ============================================================================
-- 📜 약관 동의를 열 세 개에서 **이력 표**로 옮긴다
-- 작성일: 2026-09-11 (20261279 적용 뒤 같은 날)
--
-- 왜 바로 뒤에 또 있나:
--   20261279 는 profiles 에 동의 시각·판 열 세 개를 두었다. 적용한 뒤 사용자가 요구를 더했다 —
--   기존 교사는 첫 동의(가입일 소급)를 그대로 두고, 2026-09-14 개정판에 다음 로그인 때
--   **추가로** 동의한다. 둘 다 남아야 한다. 열 세 개로는 한 번밖에 못 적는다.
--   적용된 마이그레이션은 고치지 않는다는 규칙대로 새 장을 쓴다.
--
-- 무엇을:
--   1) policy_consents 이력 표. 판마다 한 줄. 종류는 signup / reconsent / backfill.
--   2) 20261279 가 profiles 에 소급 기록한 568명을 표로 옮긴다(kind='backfill').
--   3) profiles 의 열 세 개를 없앤다 — 두 곳에 두면 어긋난다.
--   4) record_policy_consent_v1 을 표에 쓰는 판으로 바꾸고(종류 인자 추가),
--      화면이 "어느 판까지 동의했나" 물을 get_my_policy_consent_v1 을 더한다.
--   confirm_class_student_consent_v1 과 classes 의 열은 20261279 그대로 쓴다.
-- ============================================================================

BEGIN;

-- ── 1) 이력 표 ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.policy_consents (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    policy_version    TEXT NOT NULL,
    -- signup: 가입 때 / reconsent: 개정판에 다시 동의 / backfill: 기록 없던 시절을 가입일로 소급
    kind              TEXT NOT NULL CHECK (kind IN ('signup', 'reconsent', 'backfill')),
    terms_agreed_at   TIMESTAMPTZ NOT NULL,
    privacy_agreed_at TIMESTAMPTZ NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT policy_consents_version_shape CHECK (policy_version = 'backfill' OR policy_version ~ '^\d{4}-\d{2}-\d{2}$'),
    CONSTRAINT policy_consents_once_per_version UNIQUE (user_id, policy_version)
);
COMMENT ON TABLE public.policy_consents IS '교사의 이용약관·개인정보 처리방침 동의 이력. 판마다 한 줄. 원본 판 이름은 src/constants/policyVersion.js.';
CREATE INDEX IF NOT EXISTS idx_policy_consents_user_created ON public.policy_consents (user_id, created_at DESC);

-- 표는 브라우저 역할에 열지 않는다. 읽고 쓰는 길은 RPC 뿐이다(2026-09-09 보안 점검 원칙).
ALTER TABLE public.policy_consents ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.policy_consents FROM PUBLIC, anon, authenticated;

-- ── 2) 20261279 의 소급 기록을 표로 옮긴다 ────────────────────────────────
INSERT INTO public.policy_consents (user_id, policy_version, kind, terms_agreed_at, privacy_agreed_at, created_at)
SELECT id, 'backfill', 'backfill', terms_agreed_at, privacy_agreed_at, terms_agreed_at
FROM public.profiles
WHERE role = 'TEACHER' AND agreed_policy_version = 'backfill' AND terms_agreed_at IS NOT NULL
ON CONFLICT (user_id, policy_version) DO NOTHING;

-- 20261279 뒤에 가입해 실제 판으로 기록된 교사가 있으면 그것도 옮긴다(signup).
INSERT INTO public.policy_consents (user_id, policy_version, kind, terms_agreed_at, privacy_agreed_at, created_at)
SELECT id, agreed_policy_version, 'signup', terms_agreed_at, privacy_agreed_at, terms_agreed_at
FROM public.profiles
WHERE role = 'TEACHER' AND agreed_policy_version ~ '^\d{4}-\d{2}-\d{2}$' AND terms_agreed_at IS NOT NULL
ON CONFLICT (user_id, policy_version) DO NOTHING;

-- 옮긴 수가 맞는지 확인하고 나서야 열을 지운다.
DO $$
DECLARE v_src INTEGER; v_dst INTEGER;
BEGIN
    SELECT count(*) INTO v_src FROM public.profiles WHERE role = 'TEACHER' AND terms_agreed_at IS NOT NULL;
    SELECT count(DISTINCT user_id) INTO v_dst FROM public.policy_consents;
    IF v_dst < v_src THEN
        RAISE EXCEPTION '동의 기록을 옮기다 빠졌습니다: profiles %명, 표 %명', v_src, v_dst;
    END IF;
END;
$$;

-- ── 3) profiles 의 열 세 개를 없앤다 ──────────────────────────────────────
ALTER TABLE public.profiles
    DROP COLUMN IF EXISTS terms_agreed_at,
    DROP COLUMN IF EXISTS privacy_agreed_at,
    DROP COLUMN IF EXISTS agreed_policy_version;

-- ── 4) RPC ───────────────────────────────────────────────────────────────────

-- 내가 어느 판까지 동의했는지. 화면이 현재 판과 견줘 추가 동의가 필요한지 정한다.
CREATE OR REPLACE FUNCTION public.get_my_policy_consent_v1()
RETURNS JSONB
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
    SELECT jsonb_build_object(
        'version', 1,
        'agreed_versions', COALESCE((
            SELECT jsonb_agg(policy_version ORDER BY created_at)
            FROM public.policy_consents WHERE user_id = auth.uid()
        ), '[]'::JSONB)
    );
$$;

-- 옛 서명(TEXT 하나)은 지우고 종류 인자를 받는 판으로 바꾼다.
DROP FUNCTION IF EXISTS public.record_policy_consent_v1(TEXT);

CREATE OR REPLACE FUNCTION public.record_policy_consent_v1(p_version TEXT, p_kind TEXT DEFAULT 'signup')
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_version TEXT := btrim(COALESCE(p_version, ''));
BEGIN
    IF auth.uid() IS NULL THEN
        RAISE EXCEPTION '로그인이 필요합니다.' USING ERRCODE = '42501';
    END IF;
    IF v_version !~ '^\d{4}-\d{2}-\d{2}$' THEN
        RAISE EXCEPTION '약관 판 형식이 올바르지 않습니다.' USING ERRCODE = '22023';
    END IF;
    -- backfill 은 서버가 소급할 때만 쓴다. 클라이언트가 만들 수 없다.
    IF p_kind NOT IN ('signup', 'reconsent') THEN
        RAISE EXCEPTION '동의 종류가 올바르지 않습니다.' USING ERRCODE = '22023';
    END IF;

    -- 같은 판에 두 번 동의해도 한 줄만 남는다. 시각은 서버가 찍는다.
    INSERT INTO public.policy_consents (user_id, policy_version, kind, terms_agreed_at, privacy_agreed_at)
    VALUES (auth.uid(), v_version, p_kind, NOW(), NOW())
    ON CONFLICT (user_id, policy_version) DO NOTHING;

    RETURN jsonb_build_object('version', 1, 'policy_version', v_version, 'kind', p_kind, 'agreed_at', NOW());
END;
$$;

REVOKE ALL ON FUNCTION public.get_my_policy_consent_v1() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.record_policy_consent_v1(TEXT, TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_my_policy_consent_v1() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.record_policy_consent_v1(TEXT, TEXT) TO authenticated, service_role;

COMMIT;

NOTIFY pgrst, 'reload schema';
