const INLINE_CHOICES_PATTERN = /\(([^()]+)\)/g;

const createQuizQuestion = (number, question, answer, explanation, customChoices) => {
    const inlineChoices = [...question.matchAll(INLINE_CHOICES_PATTERN)]
        .flatMap((match) => match[1].split('/').map((choice) => choice.trim()));
    const answerParts = answer.split(',').map((part) => part.trim());
    let answerIndex = 0;
    const solution = question.replace(
        INLINE_CHOICES_PATTERN,
        () => answerParts.at(answerIndex++) || answer
    );

    return Object.freeze({
        id: `spelling-quiz-${String(number).padStart(3, '0')}`,
        number,
        question,
        prompt: question.replace(INLINE_CHOICES_PATTERN, '＿＿＿＿'),
        choices: Object.freeze(customChoices || [...new Set(inlineChoices)]),
        answer,
        explanation,
        solution
    });
};

export const ELEMENTARY_SPELLING_QUIZ_QUESTIONS = Object.freeze([
    createQuizQuestion(1, '이제 집에 가도 (되 / 돼).', '돼', '‘되어’로 바꿀 수 있으면 ‘돼’를 써요.'),
    createQuizQuestion(2, '나는 훌륭한 사람이 (될 / 됄) 거야.', '될', '‘됄’이라는 표현은 없어요.'),
    createQuizQuestion(3, '그렇게 하면 (안되 / 안 돼).', '안 돼', '‘안’은 뒤의 ‘돼’와 띄어 써요.'),
    createQuizQuestion(4, '준비가 다 (됬어 / 됐어).', '됐어', '‘되었어’가 줄면 ‘됐어’가 돼요.'),
    createQuizQuestion(5, '숙제를 다 하면 게임을 해도 (된데 / 된대).', '된대', '‘된다고 해’가 줄어든 말은 ‘된대’예요.'),
    createQuizQuestion(6, '오늘은 학교에 (안 / 않) 간다.', '안', '‘안’은 ‘아니’가 줄어든 말이에요.'),
    createQuizQuestion(7, '숙제를 하지 (안았다 / 않았다).', '않았다', '‘-지 않다’의 과거형은 ‘-지 않았다’예요.'),
    createQuizQuestion(8, '밥을 먹지 (안고 / 않고) 나왔다.', '않고', '‘-지 않고’가 바른 표현이에요.'),
    createQuizQuestion(9, '나는 매운 음식을 잘 먹지 (안는다 / 않는다).', '않는다', '‘-지 않는다’라고 써요.'),
    createQuizQuestion(10, '오늘은 숙제를 (안 했다 / 않았다).', '안 했다', '‘안 했다’로 쓰며 ‘하지 않았다’라고 바꿔 쓸 수도 있어요.'),
    createQuizQuestion(11, '(왠 / 웬) 사람이 우리 집에 찾아왔다.', '웬', '‘어찌 된’이라는 뜻일 때에는 ‘웬’을 써요.'),
    createQuizQuestion(12, '오늘은 (왠지 / 웬지) 기분이 좋다.', '왠지', '‘왜인지’가 줄어든 말은 ‘왠지’예요.'),
    createQuizQuestion(13, '이게 (왠일 / 웬일)이야?', '웬일', '‘웬일’이 바른 표현이에요.'),
    createQuizQuestion(14, '(왠만하면 / 웬만하면) 친구와 사이좋게 지내자.', '웬만하면', '‘웬만하다’가 바른 말이에요.'),
    createQuizQuestion(15, '방학까지 (몇일 / 며칠) 남았니?', '며칠', '‘몇일’이 아니라 ‘며칠’이라고 써요.'),
    createQuizQuestion(16, '너 생일이 몇 월 (몇 일 / 며칠)이야?', '며칠', '날짜를 물을 때에도 ‘며칠’을 써요.'),
    createQuizQuestion(17, '친구를 (오랫만에 / 오랜만에) 만났다.', '오랜만에', '‘오랫만’이 아니라 ‘오랜만’이라고 써요.'),
    createQuizQuestion(18, '우리는 (오랜동안 / 오랫동안) 이야기를 나눴다.', '오랫동안', '긴 시간 동안이라는 뜻은 ‘오랫동안’이에요.'),
    createQuizQuestion(19, '아이스크림이 (금새 / 금세) 녹았다.', '금세', '아주 짧은 시간 안에라는 뜻은 ‘금세’예요.'),
    createQuizQuestion(20, '벌써 숙제를 끝냈다니 정말 (금새 / 금세) 했구나.', '금세', '‘금시에’가 줄어든 말은 ‘금세’예요.'),
    createQuizQuestion(21, '저녁을 먹고 (설겆이 / 설거지)를 했다.', '설거지', '‘설거지’가 표준어예요.'),
    createQuizQuestion(22, '교실을 (깨끗히 / 깨끗이) 청소했다.', '깨끗이', '‘깨끗이’가 바른 표현이에요.'),
    createQuizQuestion(23, '시험지를 (꼼꼼이 / 꼼꼼히) 살펴보았다.', '꼼꼼히', '‘꼼꼼히’가 바른 표현이에요.'),
    createQuizQuestion(24, '의자에 (가만이 / 가만히) 앉아 있었다.', '가만히', '‘가만히’가 바른 표현이에요.'),
    createQuizQuestion(25, '문제를 (곰곰히 / 곰곰이) 생각했다.', '곰곰이', '‘곰곰이’가 바른 표현이에요.'),
    createQuizQuestion(26, '시간이 날 때마다 (틈틈히 / 틈틈이) 책을 읽었다.', '틈틈이', '‘틈틈이’가 바른 표현이에요.'),
    createQuizQuestion(27, '선생님께서 숙제를 (일일히 / 일일이) 확인하셨다.', '일일이', '‘일일이’가 바른 표현이에요.'),
    createQuizQuestion(28, '내 생각을 (솔직이 / 솔직히) 말했다.', '솔직히', '‘솔직히’가 바른 표현이에요.'),
    createQuizQuestion(29, '친구의 말을 (자세이 / 자세히) 들어 보았다.', '자세히', '‘자세히’가 바른 표현이에요.'),
    createQuizQuestion(30, '발표를 (천천이 / 천천히) 시작했다.', '천천히', '‘천천히’가 바른 표현이에요.'),
    createQuizQuestion(31, '감기가 어제보다 (낳았다 / 나았다).', '나았다', '병이 좋아졌다는 뜻의 기본형은 ‘낫다’예요.'),
    createQuizQuestion(32, '이 약을 먹으면 감기가 빨리 (낳을 / 나을) 거야.', '나을', '병이 좋아지는 것은 ‘낫다’이므로 ‘나을’이라고 써요.'),
    createQuizQuestion(33, '강아지가 새끼를 (나았다 / 낳았다).', '낳았다', '새끼를 몸 밖으로 내놓는 것은 ‘낳다’예요.'),
    createQuizQuestion(34, '이 의자는 저 의자보다 높이가 (낫다 / 낮다).', '낮다', '높이가 아래에 있다는 뜻은 ‘낮다’예요.'),
    createQuizQuestion(35, '나는 이 방법이 더 (낫다 / 낮다)고 생각한다.', '낫다', '더 좋다는 뜻은 ‘낫다’예요.'),
    createQuizQuestion(36, '퀴즈의 정답을 (맞췄다 / 맞혔다).', '맞혔다', '정답을 알아내는 것은 ‘맞히다’예요.'),
    createQuizQuestion(37, '친구와 서로 답을 (맞혀 / 맞춰) 보았다.', '맞춰', '서로 비교해 같게 하는 것은 ‘맞추다’예요.'),
    createQuizQuestion(38, '시계를 정확한 시간에 (맞혔다 / 맞췄다).', '맞췄다', '기준에 맞게 조정하는 것은 ‘맞추다’예요.'),
    createQuizQuestion(39, '선생님께서 수학을 (가리켜 / 가르쳐) 주셨다.', '가르쳐', '지식이나 방법을 알려 주는 것은 ‘가르치다’예요.'),
    createQuizQuestion(40, '친구가 손가락으로 하늘을 (가르쳤다 / 가리켰다).', '가리켰다', '방향이나 대상을 나타내는 것은 ‘가리키다’예요.'),
    createQuizQuestion(41, '운동장에서 지갑을 (잊어버렸다 / 잃어버렸다).', '잃어버렸다', '가지고 있던 물건이 없어지는 것은 ‘잃어버리다’예요.'),
    createQuizQuestion(42, '친구와의 약속을 (잃어버렸다 / 잊어버렸다).', '잊어버렸다', '기억하지 못하게 되는 것은 ‘잊어버리다’예요.'),
    createQuizQuestion(43, '벽에 사진을 (부쳤다 / 붙였다).', '붙였다', '달라붙게 하는 것은 ‘붙이다’예요.'),
    createQuizQuestion(44, '할머니께 편지를 (붙였다 / 부쳤다).', '부쳤다', '우편으로 보내는 것은 ‘부치다’예요.'),
    createQuizQuestion(45, '소포를 우체국에서 (붙였다 / 부쳤다).', '부쳤다', '우편으로 보내는 것은 ‘부치다’예요.'),
    createQuizQuestion(46, '이름표를 가슴에 (부쳤다 / 붙였다).', '붙였다', '물건을 달라붙게 하는 것은 ‘붙이다’예요.'),
    createQuizQuestion(47, '가방을 어깨에 (맸다 / 멨다).', '멨다', '어깨에 걸치는 것은 ‘메다’예요.'),
    createQuizQuestion(48, '신발 끈을 단단히 (멨다 / 맸다).', '맸다', '끈을 묶는 것은 ‘매다’예요.'),
    createQuizQuestion(49, '안전띠를 (메었다 / 매었다).', '매었다', '끈이나 띠를 묶는 것은 ‘매다’예요.'),
    createQuizQuestion(50, '무거운 배낭을 등에 (맸다 / 멨다).', '멨다', '등이나 어깨에 걸치는 것은 ‘메다’예요.'),
    createQuizQuestion(51, '종이에 손가락을 (배었다 / 베었다).', '베었다', '날카로운 것에 상처가 나는 것은 ‘베다’예요.'),
    createQuizQuestion(52, '옷에 음식 냄새가 (베었다 / 배었다).', '배었다', '냄새가 스며드는 것은 ‘배다’예요.'),
    createQuizQuestion(53, '땀이 옷에 (베었다 / 배었다).', '배었다', '액체가 스며드는 것은 ‘배다’예요.'),
    createQuizQuestion(54, '집에 가는 길에 문구점에 (들렸다 / 들렀다).', '들렀다', '어떤 곳을 잠깐 방문하는 것은 ‘들르다’예요.'),
    createQuizQuestion(55, '어디선가 노랫소리가 (들렀다 / 들렸다).', '들렸다', '소리가 귀에 들어오는 것은 ‘들리다’예요.'),
    createQuizQuestion(56, '오늘 학교에서 시험을 (치뤘다 / 치렀다).', '치렀다', '기본형은 ‘치르다’예요.'),
    createQuizQuestion(57, '어머니께서 김치를 (담궜다 / 담갔다).', '담갔다', '‘담그다’의 과거형은 ‘담갔다’예요.'),
    createQuizQuestion(58, '외출하기 전에 문을 (잠궜다 / 잠갔다).', '잠갔다', '‘잠그다’의 과거형은 ‘잠갔다’예요.'),
    createQuizQuestion(59, '전시된 물건을 함부로 (건들지 / 건드리지) 마세요.', '건드리지', '기본형은 ‘건드리다’예요.'),
    createQuizQuestion(60, '내 (바램 / 바람)은 가족이 행복한 것이다.', '바람', '소망을 뜻할 때에는 ‘바람’이라고 써요.'),
    createQuizQuestion(61, '네가 건강하기를 (바래 / 바라).', '바라', '무엇을 원한다는 뜻의 기본형은 ‘바라다’예요.'),
    createQuizQuestion(62, '오래된 사진의 색이 (바랬다 / 바랐다).', '바랬다', '색이 흐려지는 것은 ‘바래다’예요.'),
    createQuizQuestion(63, '너무 황당해서 (어의가 / 어이가) 없었다.', '어이가', '‘어이없다’가 바른 표현이에요.'),
    createQuizQuestion(64, '정말 (희안한 / 희한한) 일이 생겼다.', '희한한', '‘희한하다’가 바른 표현이에요.'),
    createQuizQuestion(65, '모둠에서 각자의 (역활 / 역할)을 정했다.', '역할', '‘역활’이 아니라 ‘역할’이라고 써요.'),
    createQuizQuestion(66, '수박을 (통채로 / 통째로) 가져왔다.', '통째로', '나누지 않은 덩어리 전부를 뜻할 때에는 ‘통째로’를 써요.'),
    createQuizQuestion(67, '친구가 내일 전학을 간(데 / 대).', '대', '‘간다고 해’가 줄면 ‘간대’가 돼요.'),
    createQuizQuestion(68, '동생이 이 과자가 맛있(데 / 대).', '대', '다른 사람에게 들은 말을 전할 때에는 ‘-대’를 써요.'),
    createQuizQuestion(69, '내가 어제 가 봤는(데 / 대) 정말 재미있었어.', '데', '직접 겪은 상황을 이어 말할 때에는 ‘-데’를 써요.'),
    createQuizQuestion(70, '숙제하는 (대 / 데) 한 시간이 걸렸다.', '데', '어떤 일이나 상황을 뜻하는 ‘데’를 써요.'),
    createQuizQuestion(71, '사과(든 / 던) 배(든 / 던) 하나 골라라.', '든, 든', '선택을 나타낼 때에는 ‘든’을 써요.', ['든, 든', '던, 던']),
    createQuizQuestion(72, '내가 어제 먹었(든 / 던) 빵이다.', '던', '지난 일을 떠올릴 때에는 ‘-던’을 써요.'),
    createQuizQuestion(73, '어디에 가(든 / 던) 연락해 줘.', '든', '어느 것을 선택해도 된다는 뜻에는 ‘-든’을 써요.'),
    createQuizQuestion(74, '예전에 자주 놀(든 / 던) 놀이터다.', '던', '과거의 경험을 나타낼 때에는 ‘-던’을 써요.'),
    createQuizQuestion(75, '모르는 (채 / 체)하고 지나갔다.', '체', '그런 척한다는 뜻에는 ‘체’를 써요.'),
    createQuizQuestion(76, '신발을 신은 (체 / 채) 방에 들어왔다.', '채', '어떤 상태가 그대로 이어진다는 뜻에는 ‘채’를 써요.'),
    createQuizQuestion(77, '자는 (채 / 체) 눈을 감고 있었다.', '체', '실제로 자지 않고 자는 척한다는 뜻에는 ‘체’를 써요.'),
    createQuizQuestion(78, '가방을 멘 (체 / 채) 의자에 앉았다.', '채', '가방을 멘 상태가 계속된다는 뜻에는 ‘채’를 써요.'),
    createQuizQuestion(79, '이것은 제 책(에요 / 이에요).', '이에요', '받침 있는 말 뒤에는 ‘이에요’를 써요.'),
    createQuizQuestion(80, '저는 민수(에요 / 예요).', '예요', '받침 없는 말 뒤에는 ‘예요’를 써요.'),
    createQuizQuestion(81, '저 사람은 우리 선생님(이예요 / 이에요).', '이에요', '‘이예요’가 아니라 ‘이에요’라고 써요.'),
    createQuizQuestion(82, '내일 비가 올 (거에요 / 거예요).', '거예요', '‘것이에요’가 줄면 ‘거예요’가 돼요.'),
    createQuizQuestion(83, '내가 청소를 (할께 / 할게).', '할게', '약속이나 의지를 나타내는 어미는 ‘-ㄹ게’예요.'),
    createQuizQuestion(84, '조금 있다가 전화(할께 / 할게).', '할게', '‘-ㄹ께’가 아니라 ‘-ㄹ게’라고 써요.'),
    createQuizQuestion(85, '나도 같이 (갈께 / 갈게).', '갈게', '‘-ㄹ게’로 써요.'),
    createQuizQuestion(86, '그때 같이 (갈껄 / 갈걸) 그랬다.', '갈걸', '아쉬움을 나타내는 어미는 ‘-ㄹ걸’이에요.'),
    createQuizQuestion(87, '나도 한 번 해 (볼껄 / 볼걸).', '볼걸', '어미 ‘-ㄹ걸’은 된소리로 적지 않아요.'),
    createQuizQuestion(88, '나는 혼자서도 (할수 있다 / 할 수 있다).', '할 수 있다', '의존 명사 ‘수’는 앞말과 띄어 써요.'),
    createQuizQuestion(89, '내일 도서관에 (갈것이다 / 갈 것이다).', '갈 것이다', '의존 명사 ‘것’은 앞말과 띄어 써요.'),
    createQuizQuestion(90, '사과를 (한개 / 한 개) 먹었다.', '한 개', '단위를 나타내는 ‘개’는 앞말과 띄어 써요.'),
    createQuizQuestion(91, '운동장에 학생 (세명 / 세 명)이 있다.', '세 명', '사람을 세는 ‘명’은 앞말과 띄어 써요.'),
    createQuizQuestion(92, '물을 (두잔 / 두 잔) 마셨다.', '두 잔', '단위를 나타내는 ‘잔’은 앞말과 띄어 써요.'),
    createQuizQuestion(93, '나도 (한번 / 한 번) 해 보고 싶다.', '한 번', '횟수를 나타낼 때에는 ‘한 번’으로 띄어 써요.'),
    createQuizQuestion(94, '밥을 먹은 (후에 / 후 에) 운동했다.', '후에', '조사 ‘에’는 앞말에 붙여 써요.'),
    createQuizQuestion(95, '곧 비가 올 (것같다 / 것 같다).', '것 같다', '‘것’은 앞말과 띄어 써요.'),
    createQuizQuestion(96, '숙제를 다 (한후 / 한 후) 놀았다.', '한 후', '‘후’는 앞말과 띄어 써요.'),
    createQuizQuestion(97, '집에 (갈때 / 갈 때) 비가 왔다.', '갈 때', '‘때’는 앞말과 띄어 써요.'),
    createQuizQuestion(98, '밥을 (먹은뒤 / 먹은 뒤) 이를 닦았다.', '먹은 뒤', '‘뒤’는 앞말과 띄어 써요.'),
    createQuizQuestion(99, '아는 (대로 / 데로) 설명해 봐.', '대로', '‘어떤 모양이나 상태와 같이’라는 뜻에는 ‘대로’를 써요.'),
    createQuizQuestion(100, '선생님 말씀(데로 / 대로) 따라 했다.', '대로', '‘데로’가 아니라 조사 ‘대로’를 앞말에 붙여 써요.')
]);

export const getElementarySpellingQuizQuestions = () => ELEMENTARY_SPELLING_QUIZ_QUESTIONS;
